// NodeAgent is the gRPC surface of dcnetlab-node-agent, the
// process supervisor running inside every lab server container. The
// controller is its only client, reaching it over the containerlab
// management network. By design there is no arbitrary-command RPC:
// the agent only installs packages from the controller's repository
// and supervises declared programs running out of them.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nodeagent/v1/nodeagent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_InstallPackage_FullMethodName = "/nodeagent.v1.NodeAgent/InstallPackage"
	NodeAgent_RemovePackage_FullMethodName  = "/nodeagent.v1.NodeAgent/RemovePackage"
	NodeAgent_Install_FullMethodName        = "/nodeagent.v1.NodeAgent/Install"
	NodeAgent_Start_FullMethodName          = "/nodeagent.v1.NodeAgent/Start"
	NodeAgent_Stop_FullMethodName           = "/nodeagent.v1.NodeAgent/Stop"
	NodeAgent_Remove_FullMethodName         = "/nodeagent.v1.NodeAgent/Remove"
	NodeAgent_List_FullMethodName           = "/nodeagent.v1.NodeAgent/List"
	NodeAgent_ListPackages_FullMethodName   = "/nodeagent.v1.NodeAgent/ListPackages"
	NodeAgent_TailLogs_FullMethodName       = "/nodeagent.v1.NodeAgent/TailLogs"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeAgentClient interface {
	// InstallPackage downloads a package archive from the controller's
	// repository, verifies its checksum and unpacks it under the
	// package store. Installing an already present version is a no-op.
	InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*InstallPackageReply, error)
	// RemovePackage deletes locally installed package versions; those
	// referenced by installed programs are kept and reported.
	RemovePackage(ctx context.Context, in *RemovePackageRequest, opts ...grpc.CallOption) (*RemovePackageReply, error)
	// Install registers (or replaces) a program definition; the
	// program must not be running and its package must be installed.
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*ProgramInfo, error)
	// Start launches a program and begins supervising it according to
	// its restart policy.
	Start(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*ProgramInfo, error)
	// Stop terminates a program (SIGTERM, then SIGKILL) and disables
	// restarts until the next Start.
	Stop(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*ProgramInfo, error)
	// Remove stops a program and deletes its definition and logs.
	Remove(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*RemoveReply, error)
	// List returns every installed program with its live status.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	// ListPackages returns every complete package version in the local
	// store.
	ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesReply, error)
	// TailLogs returns the last lines of a program's combined
	// stdout/stderr log.
	TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (*TailLogsReply, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*InstallPackageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallPackageReply)
	err := c.cc.Invoke(ctx, NodeAgent_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) RemovePackage(ctx context.Context, in *RemovePackageRequest, opts ...grpc.CallOption) (*RemovePackageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePackageReply)
	err := c.cc.Invoke(ctx, NodeAgent_RemovePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (*ProgramInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramInfo)
	err := c.cc.Invoke(ctx, NodeAgent_Install_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Start(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*ProgramInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramInfo)
	err := c.cc.Invoke(ctx, NodeAgent_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Stop(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*ProgramInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramInfo)
	err := c.cc.Invoke(ctx, NodeAgent_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Remove(ctx context.Context, in *ProgramRef, opts ...grpc.CallOption) (*RemoveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveReply)
	err := c.cc.Invoke(ctx, NodeAgent_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReply)
	err := c.cc.Invoke(ctx, NodeAgent_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackagesReply)
	err := c.cc.Invoke(ctx, NodeAgent_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (*TailLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TailLogsReply)
	err := c.cc.Invoke(ctx, NodeAgent_TailLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
type NodeAgentServer interface {
	// InstallPackage downloads a package archive from the controller's
	// repository, verifies its checksum and unpacks it under the
	// package store. Installing an already present version is a no-op.
	InstallPackage(context.Context, *InstallPackageRequest) (*InstallPackageReply, error)
	// RemovePackage deletes locally installed package versions; those
	// referenced by installed programs are kept and reported.
	RemovePackage(context.Context, *RemovePackageRequest) (*RemovePackageReply, error)
	// Install registers (or replaces) a program definition; the
	// program must not be running and its package must be installed.
	Install(context.Context, *InstallRequest) (*ProgramInfo, error)
	// Start launches a program and begins supervising it according to
	// its restart policy.
	Start(context.Context, *ProgramRef) (*ProgramInfo, error)
	// Stop terminates a program (SIGTERM, then SIGKILL) and disables
	// restarts until the next Start.
	Stop(context.Context, *ProgramRef) (*ProgramInfo, error)
	// Remove stops a program and deletes its definition and logs.
	Remove(context.Context, *ProgramRef) (*RemoveReply, error)
	// List returns every installed program with its live status.
	List(context.Context, *ListRequest) (*ListReply, error)
	// ListPackages returns every complete package version in the local
	// store.
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesReply, error)
	// TailLogs returns the last lines of a program's combined
	// stdout/stderr log.
	TailLogs(context.Context, *TailLogsRequest) (*TailLogsReply, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) InstallPackage(context.Context, *InstallPackageRequest) (*InstallPackageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedNodeAgentServer) RemovePackage(context.Context, *RemovePackageRequest) (*RemovePackageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePackage not implemented")
}
func (UnimplementedNodeAgentServer) Install(context.Context, *InstallRequest) (*ProgramInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedNodeAgentServer) Start(context.Context, *ProgramRef) (*ProgramInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedNodeAgentServer) Stop(context.Context, *ProgramRef) (*ProgramInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedNodeAgentServer) Remove(context.Context, *ProgramRef) (*RemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedNodeAgentServer) List(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedNodeAgentServer) ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedNodeAgentServer) TailLogs(context.Context, *TailLogsRequest) (*TailLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TailLogs not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call pancis, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).InstallPackage(ctx, req.(*InstallPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_RemovePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RemovePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RemovePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RemovePackage(ctx, req.(*RemovePackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Install_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Install(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Install_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Install(ctx, req.(*InstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Start(ctx, req.(*ProgramRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Stop(ctx, req.(*ProgramRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Remove(ctx, req.(*ProgramRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ListPackages(ctx, req.(*ListPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_TailLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TailLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).TailLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_TailLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).TailLogs(ctx, req.(*TailLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeagent.v1.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallPackage",
			Handler:    _NodeAgent_InstallPackage_Handler,
		},
		{
			MethodName: "RemovePackage",
			Handler:    _NodeAgent_RemovePackage_Handler,
		},
		{
			MethodName: "Install",
			Handler:    _NodeAgent_Install_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _NodeAgent_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _NodeAgent_Stop_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _NodeAgent_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NodeAgent_List_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _NodeAgent_ListPackages_Handler,
		},
		{
			MethodName: "TailLogs",
			Handler:    _NodeAgent_TailLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeagent/v1/nodeagent.proto",
}
