// NodeAgent is the gRPC surface of dcnetlab-node-agent, the
// process supervisor running inside every lab server container. The
// controller is its only client, reaching it over the containerlab
// management network. By design there is no arbitrary-command RPC:
// the agent only installs packages from the controller's repository
// and supervises declared programs running out of them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: nodeagent/v1/nodeagent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PackageRef identifies one package version and where to fetch it.
// url points at the controller's package repository on the management
// network; sha256 is the hex digest of the tar.gz archive.
type PackageRef struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Sha256  string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Url     string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// entrypoint is the executable inside the unpacked archive,
	// relative to its root; the agent marks it executable.
	Entrypoint string `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	// links are absolute in-container paths the agent symlinks to the
	// installed entrypoint, so tools delivered as packages appear at
	// their conventional locations (e.g. the capture tool on PATH).
	Links         []string `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageRef) Reset() {
	*x = PackageRef{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRef) ProtoMessage() {}

func (x *PackageRef) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRef.ProtoReflect.Descriptor instead.
func (*PackageRef) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{0}
}

func (x *PackageRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackageRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PackageRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PackageRef) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *PackageRef) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

type InstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       *PackageRef            `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageRequest) Reset() {
	*x = InstallPackageRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageRequest) ProtoMessage() {}

func (x *InstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{1}
}

func (x *InstallPackageRequest) GetPackage() *PackageRef {
	if x != nil {
		return x.Package
	}
	return nil
}

type InstallPackageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageReply) Reset() {
	*x = InstallPackageReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageReply) ProtoMessage() {}

func (x *InstallPackageReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageReply.ProtoReflect.Descriptor instead.
func (*InstallPackageReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{2}
}

type RemovePackageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// version narrows the removal to one version; empty removes every
	// version of the package not referenced by a program.
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackageRequest) Reset() {
	*x = RemovePackageRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackageRequest) ProtoMessage() {}

func (x *RemovePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackageRequest.ProtoReflect.Descriptor instead.
func (*RemovePackageRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{3}
}

func (x *RemovePackageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemovePackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RemovePackageReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Removed []string               `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	// in_use lists versions kept because installed programs reference
	// them, with the referencing program names.
	InUse         []*InUseVersion `protobuf:"bytes,2,rep,name=in_use,json=inUse,proto3" json:"in_use,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePackageReply) Reset() {
	*x = RemovePackageReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePackageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePackageReply) ProtoMessage() {}

func (x *RemovePackageReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePackageReply.ProtoReflect.Descriptor instead.
func (*RemovePackageReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{4}
}

func (x *RemovePackageReply) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *RemovePackageReply) GetInUse() []*InUseVersion {
	if x != nil {
		return x.InUse
	}
	return nil
}

// InUseVersion is one package version kept during removal and the
// programs pinning it.
type InUseVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Programs      []string               `protobuf:"bytes,2,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InUseVersion) Reset() {
	*x = InUseVersion{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InUseVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InUseVersion) ProtoMessage() {}

func (x *InUseVersion) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InUseVersion.ProtoReflect.Descriptor instead.
func (*InUseVersion) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{5}
}

func (x *InUseVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InUseVersion) GetPrograms() []string {
	if x != nil {
		return x.Programs
	}
	return nil
}

// HealthCheck probes a running program periodically. type is process
// (the supervised process exists), tcp (a local port accepts a
// connection) or http (a GET returns a 2xx/3xx status). The probe
// targets loopback inside the server; port and path apply to tcp/http.
type HealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Port  int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Path  string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// interval_seconds is the probe period, timeout_seconds bounds one
	// probe, failure_threshold is the consecutive failures that mark
	// the program unhealthy.
	IntervalSeconds  int32 `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds   int32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	FailureThreshold int32 `protobuf:"varint,6,opt,name=failure_threshold,json=failureThreshold,proto3" json:"failure_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthCheck) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheck) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheck) GetFailureThreshold() int32 {
	if x != nil {
		return x.FailureThreshold
	}
	return 0
}

// ProgramSpec is the agent-side program definition: an entrypoint of
// an installed package version plus its arguments.
type ProgramSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PackageName    string                 `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	PackageVersion string                 `protobuf:"bytes,3,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	Entrypoint     string                 `protobuf:"bytes,4,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Args           []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	// restart_policy is Never, OnFailure or Always; oneshot programs
	// reject Always (systemd semantics).
	RestartPolicy string `protobuf:"bytes,6,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	// type is simple (long-running daemon, the default) or oneshot
	// (runs to completion), mirroring systemd service types.
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	// auto_start marks the program enabled: the agent starts it on
	// every boot of its own process (systemd: systemctl enable).
	AutoStart bool `protobuf:"varint,8,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	// liveness_check, when set, restarts the program (per restart_policy)
	// once it fails failure_threshold consecutive probes.
	LivenessCheck *HealthCheck `protobuf:"bytes,9,opt,name=liveness_check,json=livenessCheck,proto3" json:"liveness_check,omitempty"`
	// readiness_check, when set, reports whether the program is serving;
	// unlike the liveness check it never restarts, it only gates ready.
	ReadinessCheck *HealthCheck `protobuf:"bytes,10,opt,name=readiness_check,json=readinessCheck,proto3" json:"readiness_check,omitempty"`
	// startup_order sequences boot: programs start in ascending order.
	StartupOrder  int32 `protobuf:"varint,11,opt,name=startup_order,json=startupOrder,proto3" json:"startup_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramSpec) Reset() {
	*x = ProgramSpec{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramSpec) ProtoMessage() {}

func (x *ProgramSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramSpec.ProtoReflect.Descriptor instead.
func (*ProgramSpec) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramSpec) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ProgramSpec) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *ProgramSpec) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ProgramSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProgramSpec) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *ProgramSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProgramSpec) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

func (x *ProgramSpec) GetLivenessCheck() *HealthCheck {
	if x != nil {
		return x.LivenessCheck
	}
	return nil
}

func (x *ProgramSpec) GetReadinessCheck() *HealthCheck {
	if x != nil {
		return x.ReadinessCheck
	}
	return nil
}

func (x *ProgramSpec) GetStartupOrder() int32 {
	if x != nil {
		return x.StartupOrder
	}
	return 0
}

type InstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ProgramSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{8}
}

func (x *InstallRequest) GetSpec() *ProgramSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ProgramRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramRef) Reset() {
	*x = ProgramRef{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramRef) ProtoMessage() {}

func (x *ProgramRef) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramRef.ProtoReflect.Descriptor instead.
func (*ProgramRef) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{9}
}

func (x *ProgramRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ProgramInfo is the live status of one installed program. State is
// Configured, Running, Stopped or Failed.
type ProgramInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Spec      *ProgramSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	State     string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Pid       int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Restarts  int32                  `protobuf:"varint,4,opt,name=restarts,proto3" json:"restarts,omitempty"`
	LastError string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// started_at is the unix time of the last successful start, 0 when
	// never started.
	StartedAt int64 `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// health is the last liveness verdict: Unknown (no check or not yet
	// probed), Healthy or Unhealthy.
	Health string `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	// ready reflects the readiness check (true when it has no readiness
	// check but is running, or the probe last passed).
	Ready         bool `protobuf:"varint,8,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramInfo) Reset() {
	*x = ProgramInfo{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramInfo) ProtoMessage() {}

func (x *ProgramInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramInfo.ProtoReflect.Descriptor instead.
func (*ProgramInfo) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{10}
}

func (x *ProgramInfo) GetSpec() *ProgramSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ProgramInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProgramInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProgramInfo) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ProgramInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ProgramInfo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *ProgramInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ProgramInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type RemoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReply) Reset() {
	*x = RemoveReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReply) ProtoMessage() {}

func (x *RemoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReply.ProtoReflect.Descriptor instead.
func (*RemoveReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{11}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{12}
}

type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Programs      []*ProgramInfo         `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{13}
}

func (x *ListReply) GetPrograms() []*ProgramInfo {
	if x != nil {
		return x.Programs
	}
	return nil
}

type ListPackagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesRequest) Reset() {
	*x = ListPackagesRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesRequest) ProtoMessage() {}

func (x *ListPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListPackagesRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{14}
}

// InstalledPackage is one complete package version in the local
// store.
type InstalledPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledPackage) Reset() {
	*x = InstalledPackage{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPackage) ProtoMessage() {}

func (x *InstalledPackage) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPackage.ProtoReflect.Descriptor instead.
func (*InstalledPackage) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{15}
}

func (x *InstalledPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPackage) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ListPackagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []*InstalledPackage    `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPackagesReply) Reset() {
	*x = ListPackagesReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPackagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPackagesReply) ProtoMessage() {}

func (x *ListPackagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPackagesReply.ProtoReflect.Descriptor instead.
func (*ListPackagesReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{16}
}

func (x *ListPackagesReply) GetPackages() []*InstalledPackage {
	if x != nil {
		return x.Packages
	}
	return nil
}

type TailLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// lines caps the tail length; the agent applies a default and an
	// upper bound.
	Lines         int32 `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{17}
}

func (x *TailLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TailLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type TailLogsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsReply) Reset() {
	*x = TailLogsReply{}
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsReply) ProtoMessage() {}

func (x *TailLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_nodeagent_v1_nodeagent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsReply.ProtoReflect.Descriptor instead.
func (*TailLogsReply) Descriptor() ([]byte, []int) {
	return file_nodeagent_v1_nodeagent_proto_rawDescGZIP(), []int{18}
}

func (x *TailLogsReply) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_nodeagent_v1_nodeagent_proto protoreflect.FileDescriptor

const file_nodeagent_v1_nodeagent_proto_rawDesc = "" +
	"\n" +
	"\x1cnodeagent/v1/nodeagent.proto\x12\fnodeagent.v1\"\x9a\x01\n" +
	"\n" +
	"PackageRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12\x14\n" +
	"\x05links\x18\x06 \x03(\tR\x05links\"K\n" +
	"\x15InstallPackageRequest\x122\n" +
	"\apackage\x18\x01 \x01(\v2\x18.nodeagent.v1.PackageRefR\apackage\"\x15\n" +
	"\x13InstallPackageReply\"D\n" +
	"\x14RemovePackageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"a\n" +
	"\x12RemovePackageReply\x12\x18\n" +
	"\aremoved\x18\x01 \x03(\tR\aremoved\x121\n" +
	"\x06in_use\x18\x02 \x03(\v2\x1a.nodeagent.v1.InUseVersionR\x05inUse\"D\n" +
	"\fInUseVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bprograms\x18\x02 \x03(\tR\bprograms\"\xca\x01\n" +
	"\vHealthCheck\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12+\n" +
	"\x11failure_threshold\x18\x06 \x01(\x05R\x10failureThreshold\"\xa6\x03\n" +
	"\vProgramSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x03 \x01(\tR\x0epackageVersion\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x04 \x01(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12%\n" +
	"\x0erestart_policy\x18\x06 \x01(\tR\rrestartPolicy\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"auto_start\x18\b \x01(\bR\tautoStart\x12@\n" +
	"\x0eliveness_check\x18\t \x01(\v2\x19.nodeagent.v1.HealthCheckR\rlivenessCheck\x12B\n" +
	"\x0freadiness_check\x18\n" +
	" \x01(\v2\x19.nodeagent.v1.HealthCheckR\x0ereadinessCheck\x12#\n" +
	"\rstartup_order\x18\v \x01(\x05R\fstartupOrder\"?\n" +
	"\x0eInstallRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.nodeagent.v1.ProgramSpecR\x04spec\" \n" +
	"\n" +
	"ProgramRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xec\x01\n" +
	"\vProgramInfo\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.nodeagent.v1.ProgramSpecR\x04spec\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1a\n" +
	"\brestarts\x18\x04 \x01(\x05R\brestarts\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12\x16\n" +
	"\x06health\x18\a \x01(\tR\x06health\x12\x14\n" +
	"\x05ready\x18\b \x01(\bR\x05ready\"\r\n" +
	"\vRemoveReply\"\r\n" +
	"\vListRequest\"B\n" +
	"\tListReply\x125\n" +
	"\bprograms\x18\x01 \x03(\v2\x19.nodeagent.v1.ProgramInfoR\bprograms\"\x15\n" +
	"\x13ListPackagesRequest\"X\n" +
	"\x10InstalledPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"O\n" +
	"\x11ListPackagesReply\x12:\n" +
	"\bpackages\x18\x01 \x03(\v2\x1e.nodeagent.v1.InstalledPackageR\bpackages\";\n" +
	"\x0fTailLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\")\n" +
	"\rTailLogsReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent2\x92\x05\n" +
	"\tNodeAgent\x12X\n" +
	"\x0eInstallPackage\x12#.nodeagent.v1.InstallPackageRequest\x1a!.nodeagent.v1.InstallPackageReply\x12U\n" +
	"\rRemovePackage\x12\".nodeagent.v1.RemovePackageRequest\x1a .nodeagent.v1.RemovePackageReply\x12B\n" +
	"\aInstall\x12\x1c.nodeagent.v1.InstallRequest\x1a\x19.nodeagent.v1.ProgramInfo\x12<\n" +
	"\x05Start\x12\x18.nodeagent.v1.ProgramRef\x1a\x19.nodeagent.v1.ProgramInfo\x12;\n" +
	"\x04Stop\x12\x18.nodeagent.v1.ProgramRef\x1a\x19.nodeagent.v1.ProgramInfo\x12=\n" +
	"\x06Remove\x12\x18.nodeagent.v1.ProgramRef\x1a\x19.nodeagent.v1.RemoveReply\x12:\n" +
	"\x04List\x12\x19.nodeagent.v1.ListRequest\x1a\x17.nodeagent.v1.ListReply\x12R\n" +
	"\fListPackages\x12!.nodeagent.v1.ListPackagesRequest\x1a\x1f.nodeagent.v1.ListPackagesReply\x12F\n" +
	"\bTailLogs\x12\x1d.nodeagent.v1.TailLogsRequest\x1a\x1b.nodeagent.v1.TailLogsReplyB1Z/github.com/ifantsai/dcnetlab/pb/nodeagent/v1;v1b\x06proto3"

var (
	file_nodeagent_v1_nodeagent_proto_rawDescOnce sync.Once
	file_nodeagent_v1_nodeagent_proto_rawDescData []byte
)

func file_nodeagent_v1_nodeagent_proto_rawDescGZIP() []byte {
	file_nodeagent_v1_nodeagent_proto_rawDescOnce.Do(func() {
		file_nodeagent_v1_nodeagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeagent_v1_nodeagent_proto_rawDesc), len(file_nodeagent_v1_nodeagent_proto_rawDesc)))
	})
	return file_nodeagent_v1_nodeagent_proto_rawDescData
}

var file_nodeagent_v1_nodeagent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_nodeagent_v1_nodeagent_proto_goTypes = []any{
	(*PackageRef)(nil),            // 0: nodeagent.v1.PackageRef
	(*InstallPackageRequest)(nil), // 1: nodeagent.v1.InstallPackageRequest
	(*InstallPackageReply)(nil),   // 2: nodeagent.v1.InstallPackageReply
	(*RemovePackageRequest)(nil),  // 3: nodeagent.v1.RemovePackageRequest
	(*RemovePackageReply)(nil),    // 4: nodeagent.v1.RemovePackageReply
	(*InUseVersion)(nil),          // 5: nodeagent.v1.InUseVersion
	(*HealthCheck)(nil),           // 6: nodeagent.v1.HealthCheck
	(*ProgramSpec)(nil),           // 7: nodeagent.v1.ProgramSpec
	(*InstallRequest)(nil),        // 8: nodeagent.v1.InstallRequest
	(*ProgramRef)(nil),            // 9: nodeagent.v1.ProgramRef
	(*ProgramInfo)(nil),           // 10: nodeagent.v1.ProgramInfo
	(*RemoveReply)(nil),           // 11: nodeagent.v1.RemoveReply
	(*ListRequest)(nil),           // 12: nodeagent.v1.ListRequest
	(*ListReply)(nil),             // 13: nodeagent.v1.ListReply
	(*ListPackagesRequest)(nil),   // 14: nodeagent.v1.ListPackagesRequest
	(*InstalledPackage)(nil),      // 15: nodeagent.v1.InstalledPackage
	(*ListPackagesReply)(nil),     // 16: nodeagent.v1.ListPackagesReply
	(*TailLogsRequest)(nil),       // 17: nodeagent.v1.TailLogsRequest
	(*TailLogsReply)(nil),         // 18: nodeagent.v1.TailLogsReply
}
var file_nodeagent_v1_nodeagent_proto_depIdxs = []int32{
	0,  // 0: nodeagent.v1.InstallPackageRequest.package:type_name -> nodeagent.v1.PackageRef
	5,  // 1: nodeagent.v1.RemovePackageReply.in_use:type_name -> nodeagent.v1.InUseVersion
	6,  // 2: nodeagent.v1.ProgramSpec.liveness_check:type_name -> nodeagent.v1.HealthCheck
	6,  // 3: nodeagent.v1.ProgramSpec.readiness_check:type_name -> nodeagent.v1.HealthCheck
	7,  // 4: nodeagent.v1.InstallRequest.spec:type_name -> nodeagent.v1.ProgramSpec
	7,  // 5: nodeagent.v1.ProgramInfo.spec:type_name -> nodeagent.v1.ProgramSpec
	10, // 6: nodeagent.v1.ListReply.programs:type_name -> nodeagent.v1.ProgramInfo
	15, // 7: nodeagent.v1.ListPackagesReply.packages:type_name -> nodeagent.v1.InstalledPackage
	1,  // 8: nodeagent.v1.NodeAgent.InstallPackage:input_type -> nodeagent.v1.InstallPackageRequest
	3,  // 9: nodeagent.v1.NodeAgent.RemovePackage:input_type -> nodeagent.v1.RemovePackageRequest
	8,  // 10: nodeagent.v1.NodeAgent.Install:input_type -> nodeagent.v1.InstallRequest
	9,  // 11: nodeagent.v1.NodeAgent.Start:input_type -> nodeagent.v1.ProgramRef
	9,  // 12: nodeagent.v1.NodeAgent.Stop:input_type -> nodeagent.v1.ProgramRef
	9,  // 13: nodeagent.v1.NodeAgent.Remove:input_type -> nodeagent.v1.ProgramRef
	12, // 14: nodeagent.v1.NodeAgent.List:input_type -> nodeagent.v1.ListRequest
	14, // 15: nodeagent.v1.NodeAgent.ListPackages:input_type -> nodeagent.v1.ListPackagesRequest
	17, // 16: nodeagent.v1.NodeAgent.TailLogs:input_type -> nodeagent.v1.TailLogsRequest
	2,  // 17: nodeagent.v1.NodeAgent.InstallPackage:output_type -> nodeagent.v1.InstallPackageReply
	4,  // 18: nodeagent.v1.NodeAgent.RemovePackage:output_type -> nodeagent.v1.RemovePackageReply
	10, // 19: nodeagent.v1.NodeAgent.Install:output_type -> nodeagent.v1.ProgramInfo
	10, // 20: nodeagent.v1.NodeAgent.Start:output_type -> nodeagent.v1.ProgramInfo
	10, // 21: nodeagent.v1.NodeAgent.Stop:output_type -> nodeagent.v1.ProgramInfo
	11, // 22: nodeagent.v1.NodeAgent.Remove:output_type -> nodeagent.v1.RemoveReply
	13, // 23: nodeagent.v1.NodeAgent.List:output_type -> nodeagent.v1.ListReply
	16, // 24: nodeagent.v1.NodeAgent.ListPackages:output_type -> nodeagent.v1.ListPackagesReply
	18, // 25: nodeagent.v1.NodeAgent.TailLogs:output_type -> nodeagent.v1.TailLogsReply
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_nodeagent_v1_nodeagent_proto_init() }
func file_nodeagent_v1_nodeagent_proto_init() {
	if File_nodeagent_v1_nodeagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeagent_v1_nodeagent_proto_rawDesc), len(file_nodeagent_v1_nodeagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeagent_v1_nodeagent_proto_goTypes,
		DependencyIndexes: file_nodeagent_v1_nodeagent_proto_depIdxs,
		MessageInfos:      file_nodeagent_v1_nodeagent_proto_msgTypes,
	}.Build()
	File_nodeagent_v1_nodeagent_proto = out.File
	file_nodeagent_v1_nodeagent_proto_goTypes = nil
	file_nodeagent_v1_nodeagent_proto_depIdxs = nil
}
