// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/ifantsai/dcnetlab/internal/biz"
	"github.com/ifantsai/dcnetlab/internal/conf"
	"github.com/ifantsai/dcnetlab/internal/data"
	"github.com/ifantsai/dcnetlab/internal/observer"
	"github.com/ifantsai/dcnetlab/internal/server"
	"github.com/ifantsai/dcnetlab/internal/service"
	"log/slog"
)

// Injectors from wire.go:

// wireApp builds the controller object graph from the per-layer
// ProviderSets. Regenerate wire_gen.go with `make wire`.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, slogLogger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	labRepo := data.NewLabRepo(dataData)
	store := data.NewOperationStore(dataData)
	manager := biz.NewOperationManager(store, slogLogger)
	driver, err := data.NewRuntimeDriver(confData, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	labUsecase := biz.NewLabUsecase(labRepo, manager, driver, confData, slogLogger)
	topologyRepo := data.NewTopologyRepo(dataData)
	topologyUsecase := biz.NewTopologyUsecase(topologyRepo, slogLogger)
	planRepo := data.NewPlanRepo(dataData)
	programRepo := data.NewProgramRepo(dataData)
	programAgent := data.NewProgramAgent(slogLogger)
	packageRepo := data.NewPackageRepo(dataData)
	packageUsecase, err := biz.NewPackageUsecase(packageRepo, confData, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	programUsecase := biz.NewProgramUsecase(programRepo, programAgent, driver, packageUsecase, confServer, slogLogger)
	planUsecase := biz.NewPlanUsecase(planRepo, manager, driver, programUsecase, confData, slogLogger)
	operationRepo := data.NewOperationRepo(dataData)
	operationUsecase := biz.NewOperationUsecase(operationRepo, slogLogger)
	powerRepo := data.NewPowerRepo(dataData)
	powerUsecase := biz.NewPowerUsecase(powerRepo, manager, driver, slogLogger)
	runtimeUsecase := biz.NewRuntimeUsecase(labRepo, topologyRepo, driver, slogLogger)
	dcNetLabService := service.NewDCNetLabService(labUsecase, topologyUsecase, planUsecase, operationUsecase, powerUsecase, runtimeUsecase, programUsecase, packageUsecase, slogLogger)
	terminalUsecase := biz.NewTerminalUsecase(labRepo, topologyRepo, driver, slogLogger)
	observerStore := data.NewObserverStore(dataData)
	observerObserver := observer.New(observerStore, driver, slogLogger)
	httpServer := server.NewHTTPServer(confServer, dcNetLabService, terminalUsecase, observerObserver, logger)
	grpcServer := server.NewGRPCServer(confServer, dcNetLabService, logger)
	repoServer := server.NewRepoServer(confServer, packageUsecase, slogLogger)
	app := newApp(confServer, logger, httpServer, grpcServer, repoServer, observerObserver)
	return app, func() {
		cleanup()
	}, nil
}
