// DCNetLab controller API. The protobuf definition is the single
// source of truth for the REST surface; HTTP bindings are declared
// with google.api.http annotations and served by Kratos. JSON field
// names follow the protojson camelCase mapping, which matches the
// original hand-written REST API consumed by the web UI.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dcnetlab/v1/dcnetlab.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DCNetLab_CreateLab_FullMethodName       = "/dcnetlab.v1.DCNetLab/CreateLab"
	DCNetLab_ListLabs_FullMethodName        = "/dcnetlab.v1.DCNetLab/ListLabs"
	DCNetLab_GetLab_FullMethodName          = "/dcnetlab.v1.DCNetLab/GetLab"
	DCNetLab_DeleteLab_FullMethodName       = "/dcnetlab.v1.DCNetLab/DeleteLab"
	DCNetLab_StartLab_FullMethodName        = "/dcnetlab.v1.DCNetLab/StartLab"
	DCNetLab_StopLab_FullMethodName         = "/dcnetlab.v1.DCNetLab/StopLab"
	DCNetLab_ListNodes_FullMethodName       = "/dcnetlab.v1.DCNetLab/ListNodes"
	DCNetLab_ListLinks_FullMethodName       = "/dcnetlab.v1.DCNetLab/ListLinks"
	DCNetLab_ListAllocations_FullMethodName = "/dcnetlab.v1.DCNetLab/ListAllocations"
	DCNetLab_StartNode_FullMethodName       = "/dcnetlab.v1.DCNetLab/StartNode"
	DCNetLab_StopNode_FullMethodName        = "/dcnetlab.v1.DCNetLab/StopNode"
	DCNetLab_CreatePlan_FullMethodName      = "/dcnetlab.v1.DCNetLab/CreatePlan"
	DCNetLab_GetPlan_FullMethodName         = "/dcnetlab.v1.DCNetLab/GetPlan"
	DCNetLab_ApplyPlan_FullMethodName       = "/dcnetlab.v1.DCNetLab/ApplyPlan"
	DCNetLab_GetOperation_FullMethodName    = "/dcnetlab.v1.DCNetLab/GetOperation"
	DCNetLab_ListOperations_FullMethodName  = "/dcnetlab.v1.DCNetLab/ListOperations"
	DCNetLab_ListGenerations_FullMethodName = "/dcnetlab.v1.DCNetLab/ListGenerations"
	DCNetLab_ListProfiles_FullMethodName    = "/dcnetlab.v1.DCNetLab/ListProfiles"
	DCNetLab_Healthz_FullMethodName         = "/dcnetlab.v1.DCNetLab/Healthz"
)

// DCNetLabClient is the client API for DCNetLab service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DCNetLab is the controller service: lab lifecycle, plan/apply,
// topology queries and async operation tracking.
type DCNetLabClient interface {
	// --- Labs ---
	CreateLab(ctx context.Context, in *CreateLabRequest, opts ...grpc.CallOption) (*Lab, error)
	ListLabs(ctx context.Context, in *ListLabsRequest, opts ...grpc.CallOption) (*ListLabsReply, error)
	GetLab(ctx context.Context, in *GetLabRequest, opts ...grpc.CallOption) (*Lab, error)
	DeleteLab(ctx context.Context, in *DeleteLabRequest, opts ...grpc.CallOption) (*OperationRef, error)
	// StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(ctx context.Context, in *StartLabRequest, opts ...grpc.CallOption) (*OperationRef, error)
	StopLab(ctx context.Context, in *StopLabRequest, opts ...grpc.CallOption) (*OperationRef, error)
	// --- Topology ---
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error)
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksReply, error)
	ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...grpc.CallOption) (*ListAllocationsReply, error)
	// StartNode / StopNode power a single device on and off.
	StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*Node, error)
	StopNode(ctx context.Context, in *StopNodeRequest, opts ...grpc.CallOption) (*Node, error)
	// --- Plans ---
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*Plan, error)
	GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*Plan, error)
	ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*OperationRef, error)
	// --- Operations & Generations ---
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsReply, error)
	ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...grpc.CallOption) (*ListGenerationsReply, error)
	// --- Profiles & health ---
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesReply, error)
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzReply, error)
}

type dCNetLabClient struct {
	cc grpc.ClientConnInterface
}

func NewDCNetLabClient(cc grpc.ClientConnInterface) DCNetLabClient {
	return &dCNetLabClient{cc}
}

func (c *dCNetLabClient) CreateLab(ctx context.Context, in *CreateLabRequest, opts ...grpc.CallOption) (*Lab, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lab)
	err := c.cc.Invoke(ctx, DCNetLab_CreateLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListLabs(ctx context.Context, in *ListLabsRequest, opts ...grpc.CallOption) (*ListLabsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabsReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) GetLab(ctx context.Context, in *GetLabRequest, opts ...grpc.CallOption) (*Lab, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lab)
	err := c.cc.Invoke(ctx, DCNetLab_GetLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) DeleteLab(ctx context.Context, in *DeleteLabRequest, opts ...grpc.CallOption) (*OperationRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationRef)
	err := c.cc.Invoke(ctx, DCNetLab_DeleteLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) StartLab(ctx context.Context, in *StartLabRequest, opts ...grpc.CallOption) (*OperationRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationRef)
	err := c.cc.Invoke(ctx, DCNetLab_StartLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) StopLab(ctx context.Context, in *StopLabRequest, opts ...grpc.CallOption) (*OperationRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationRef)
	err := c.cc.Invoke(ctx, DCNetLab_StopLab_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...grpc.CallOption) (*ListAllocationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllocationsReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListAllocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) StartNode(ctx context.Context, in *StartNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, DCNetLab_StartNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) StopNode(ctx context.Context, in *StopNodeRequest, opts ...grpc.CallOption) (*Node, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Node)
	err := c.cc.Invoke(ctx, DCNetLab_StopNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*Plan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plan)
	err := c.cc.Invoke(ctx, DCNetLab_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...grpc.CallOption) (*Plan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Plan)
	err := c.cc.Invoke(ctx, DCNetLab_GetPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*OperationRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationRef)
	err := c.cc.Invoke(ctx, DCNetLab_ApplyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, DCNetLab_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperationsReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...grpc.CallOption) (*ListGenerationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGenerationsReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListGenerations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesReply)
	err := c.cc.Invoke(ctx, DCNetLab_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dCNetLabClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzReply)
	err := c.cc.Invoke(ctx, DCNetLab_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DCNetLabServer is the server API for DCNetLab service.
// All implementations must embed UnimplementedDCNetLabServer
// for forward compatibility.
//
// DCNetLab is the controller service: lab lifecycle, plan/apply,
// topology queries and async operation tracking.
type DCNetLabServer interface {
	// --- Labs ---
	CreateLab(context.Context, *CreateLabRequest) (*Lab, error)
	ListLabs(context.Context, *ListLabsRequest) (*ListLabsReply, error)
	GetLab(context.Context, *GetLabRequest) (*Lab, error)
	DeleteLab(context.Context, *DeleteLabRequest) (*OperationRef, error)
	// StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(context.Context, *StartLabRequest) (*OperationRef, error)
	StopLab(context.Context, *StopLabRequest) (*OperationRef, error)
	// --- Topology ---
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksReply, error)
	ListAllocations(context.Context, *ListAllocationsRequest) (*ListAllocationsReply, error)
	// StartNode / StopNode power a single device on and off.
	StartNode(context.Context, *StartNodeRequest) (*Node, error)
	StopNode(context.Context, *StopNodeRequest) (*Node, error)
	// --- Plans ---
	CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error)
	GetPlan(context.Context, *GetPlanRequest) (*Plan, error)
	ApplyPlan(context.Context, *ApplyPlanRequest) (*OperationRef, error)
	// --- Operations & Generations ---
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsReply, error)
	ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsReply, error)
	// --- Profiles & health ---
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesReply, error)
	Healthz(context.Context, *HealthzRequest) (*HealthzReply, error)
	mustEmbedUnimplementedDCNetLabServer()
}

// UnimplementedDCNetLabServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDCNetLabServer struct{}

func (UnimplementedDCNetLabServer) CreateLab(context.Context, *CreateLabRequest) (*Lab, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLab not implemented")
}
func (UnimplementedDCNetLabServer) ListLabs(context.Context, *ListLabsRequest) (*ListLabsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLabs not implemented")
}
func (UnimplementedDCNetLabServer) GetLab(context.Context, *GetLabRequest) (*Lab, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLab not implemented")
}
func (UnimplementedDCNetLabServer) DeleteLab(context.Context, *DeleteLabRequest) (*OperationRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLab not implemented")
}
func (UnimplementedDCNetLabServer) StartLab(context.Context, *StartLabRequest) (*OperationRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLab not implemented")
}
func (UnimplementedDCNetLabServer) StopLab(context.Context, *StopLabRequest) (*OperationRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLab not implemented")
}
func (UnimplementedDCNetLabServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedDCNetLabServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedDCNetLabServer) ListAllocations(context.Context, *ListAllocationsRequest) (*ListAllocationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllocations not implemented")
}
func (UnimplementedDCNetLabServer) StartNode(context.Context, *StartNodeRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartNode not implemented")
}
func (UnimplementedDCNetLabServer) StopNode(context.Context, *StopNodeRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopNode not implemented")
}
func (UnimplementedDCNetLabServer) CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedDCNetLabServer) GetPlan(context.Context, *GetPlanRequest) (*Plan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
}
func (UnimplementedDCNetLabServer) ApplyPlan(context.Context, *ApplyPlanRequest) (*OperationRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPlan not implemented")
}
func (UnimplementedDCNetLabServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedDCNetLabServer) ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperations not implemented")
}
func (UnimplementedDCNetLabServer) ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGenerations not implemented")
}
func (UnimplementedDCNetLabServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedDCNetLabServer) Healthz(context.Context, *HealthzRequest) (*HealthzReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedDCNetLabServer) mustEmbedUnimplementedDCNetLabServer() {}
func (UnimplementedDCNetLabServer) testEmbeddedByValue()                  {}

// UnsafeDCNetLabServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DCNetLabServer will
// result in compilation errors.
type UnsafeDCNetLabServer interface {
	mustEmbedUnimplementedDCNetLabServer()
}

func RegisterDCNetLabServer(s grpc.ServiceRegistrar, srv DCNetLabServer) {
	// If the following call pancis, it indicates UnimplementedDCNetLabServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DCNetLab_ServiceDesc, srv)
}

func _DCNetLab_CreateLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).CreateLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_CreateLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).CreateLab(ctx, req.(*CreateLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListLabs(ctx, req.(*ListLabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_GetLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).GetLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_GetLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).GetLab(ctx, req.(*GetLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_DeleteLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).DeleteLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_DeleteLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).DeleteLab(ctx, req.(*DeleteLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_StartLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).StartLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_StartLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).StartLab(ctx, req.(*StartLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_StopLab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLabRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).StopLab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_StopLab_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).StopLab(ctx, req.(*StopLabRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListAllocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListAllocations(ctx, req.(*ListAllocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_StartNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).StartNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_StartNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).StartNode(ctx, req.(*StartNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_StopNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).StopNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_StopNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).StopNode(ctx, req.(*StopNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_GetPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_GetPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).GetPlan(ctx, req.(*GetPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ApplyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ApplyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ApplyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ApplyPlan(ctx, req.(*ApplyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListOperations(ctx, req.(*ListOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListGenerations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGenerationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListGenerations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListGenerations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListGenerations(ctx, req.(*ListGenerationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DCNetLab_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DCNetLabServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DCNetLab_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DCNetLabServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DCNetLab_ServiceDesc is the grpc.ServiceDesc for DCNetLab service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DCNetLab_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dcnetlab.v1.DCNetLab",
	HandlerType: (*DCNetLabServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLab",
			Handler:    _DCNetLab_CreateLab_Handler,
		},
		{
			MethodName: "ListLabs",
			Handler:    _DCNetLab_ListLabs_Handler,
		},
		{
			MethodName: "GetLab",
			Handler:    _DCNetLab_GetLab_Handler,
		},
		{
			MethodName: "DeleteLab",
			Handler:    _DCNetLab_DeleteLab_Handler,
		},
		{
			MethodName: "StartLab",
			Handler:    _DCNetLab_StartLab_Handler,
		},
		{
			MethodName: "StopLab",
			Handler:    _DCNetLab_StopLab_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _DCNetLab_ListNodes_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _DCNetLab_ListLinks_Handler,
		},
		{
			MethodName: "ListAllocations",
			Handler:    _DCNetLab_ListAllocations_Handler,
		},
		{
			MethodName: "StartNode",
			Handler:    _DCNetLab_StartNode_Handler,
		},
		{
			MethodName: "StopNode",
			Handler:    _DCNetLab_StopNode_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _DCNetLab_CreatePlan_Handler,
		},
		{
			MethodName: "GetPlan",
			Handler:    _DCNetLab_GetPlan_Handler,
		},
		{
			MethodName: "ApplyPlan",
			Handler:    _DCNetLab_ApplyPlan_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _DCNetLab_GetOperation_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _DCNetLab_ListOperations_Handler,
		},
		{
			MethodName: "ListGenerations",
			Handler:    _DCNetLab_ListGenerations_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _DCNetLab_ListProfiles_Handler,
		},
		{
			MethodName: "Healthz",
			Handler:    _DCNetLab_Healthz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dcnetlab/v1/dcnetlab.proto",
}
