// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: dcnetlab/v1/dcnetlab.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDCNetLabApplyPlan = "/dcnetlab.v1.DCNetLab/ApplyPlan"
const OperationDCNetLabCreateLab = "/dcnetlab.v1.DCNetLab/CreateLab"
const OperationDCNetLabCreatePlan = "/dcnetlab.v1.DCNetLab/CreatePlan"
const OperationDCNetLabCreateProgram = "/dcnetlab.v1.DCNetLab/CreateProgram"
const OperationDCNetLabDeleteLab = "/dcnetlab.v1.DCNetLab/DeleteLab"
const OperationDCNetLabDeletePackage = "/dcnetlab.v1.DCNetLab/DeletePackage"
const OperationDCNetLabDeleteProgram = "/dcnetlab.v1.DCNetLab/DeleteProgram"
const OperationDCNetLabGetLab = "/dcnetlab.v1.DCNetLab/GetLab"
const OperationDCNetLabGetNodeBGP = "/dcnetlab.v1.DCNetLab/GetNodeBGP"
const OperationDCNetLabGetNodeBGPTable = "/dcnetlab.v1.DCNetLab/GetNodeBGPTable"
const OperationDCNetLabGetNodeFIB = "/dcnetlab.v1.DCNetLab/GetNodeFIB"
const OperationDCNetLabGetNodeInventory = "/dcnetlab.v1.DCNetLab/GetNodeInventory"
const OperationDCNetLabGetNodeMetrics = "/dcnetlab.v1.DCNetLab/GetNodeMetrics"
const OperationDCNetLabGetNodeMetricsHistory = "/dcnetlab.v1.DCNetLab/GetNodeMetricsHistory"
const OperationDCNetLabGetNodeRoutes = "/dcnetlab.v1.DCNetLab/GetNodeRoutes"
const OperationDCNetLabGetNodeRuntime = "/dcnetlab.v1.DCNetLab/GetNodeRuntime"
const OperationDCNetLabGetOperation = "/dcnetlab.v1.DCNetLab/GetOperation"
const OperationDCNetLabGetPlan = "/dcnetlab.v1.DCNetLab/GetPlan"
const OperationDCNetLabGetProgramLogs = "/dcnetlab.v1.DCNetLab/GetProgramLogs"
const OperationDCNetLabHealthz = "/dcnetlab.v1.DCNetLab/Healthz"
const OperationDCNetLabInstallPackage = "/dcnetlab.v1.DCNetLab/InstallPackage"
const OperationDCNetLabListAllocations = "/dcnetlab.v1.DCNetLab/ListAllocations"
const OperationDCNetLabListGenerations = "/dcnetlab.v1.DCNetLab/ListGenerations"
const OperationDCNetLabListLabs = "/dcnetlab.v1.DCNetLab/ListLabs"
const OperationDCNetLabListLinks = "/dcnetlab.v1.DCNetLab/ListLinks"
const OperationDCNetLabListNodes = "/dcnetlab.v1.DCNetLab/ListNodes"
const OperationDCNetLabListOperations = "/dcnetlab.v1.DCNetLab/ListOperations"
const OperationDCNetLabListPackages = "/dcnetlab.v1.DCNetLab/ListPackages"
const OperationDCNetLabListProfiles = "/dcnetlab.v1.DCNetLab/ListProfiles"
const OperationDCNetLabListPrograms = "/dcnetlab.v1.DCNetLab/ListPrograms"
const OperationDCNetLabStartLab = "/dcnetlab.v1.DCNetLab/StartLab"
const OperationDCNetLabStartNode = "/dcnetlab.v1.DCNetLab/StartNode"
const OperationDCNetLabStartProgram = "/dcnetlab.v1.DCNetLab/StartProgram"
const OperationDCNetLabStopLab = "/dcnetlab.v1.DCNetLab/StopLab"
const OperationDCNetLabStopNode = "/dcnetlab.v1.DCNetLab/StopNode"
const OperationDCNetLabStopProgram = "/dcnetlab.v1.DCNetLab/StopProgram"
const OperationDCNetLabUpgradeProgram = "/dcnetlab.v1.DCNetLab/UpgradeProgram"
const OperationDCNetLabUploadPackage = "/dcnetlab.v1.DCNetLab/UploadPackage"

type DCNetLabHTTPServer interface {
	ApplyPlan(context.Context, *ApplyPlanRequest) (*OperationRef, error)
	// CreateLab --- Labs ---
	CreateLab(context.Context, *CreateLabRequest) (*Lab, error)
	// CreatePlan --- Plans ---
	CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error)
	// CreateProgram --- Programs ---
	// Programs are supervised processes on lab servers, each running
	// the entrypoint of an installed Package version, managed through
	// the per-server dcnetlab-server-agent.
	CreateProgram(context.Context, *CreateProgramRequest) (*CreateProgramReply, error)
	DeleteLab(context.Context, *DeleteLabRequest) (*OperationRef, error)
	DeletePackage(context.Context, *DeletePackageRequest) (*DeletePackageReply, error)
	DeleteProgram(context.Context, *ProgramOpRequest) (*DeleteProgramReply, error)
	GetLab(context.Context, *GetLabRequest) (*Lab, error)
	// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
	// by the FRR compiler from the topology model: eBGP neighbors over
	// fabric links, the MLAG iBGP session and the leaf's dynamic server
	// peer-group. Empty for nodes that do not run BGP.
	GetNodeBGP(context.Context, *GetNodeBGPRequest) (*NodeBGP, error)
	// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
	// node (`show ip bgp`): every candidate path per prefix, before
	// best-path selection reduces them to the RIB entry.
	GetNodeBGPTable(context.Context, *GetNodeBGPTableRequest) (*NodeBGPTable, error)
	// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
	// deployed node (`ip route`): what actually forwards packets, as
	// installed by zebra from the RIB.
	GetNodeFIB(context.Context, *GetNodeFIBRequest) (*NodeFIB, error)
	// GetNodeInventory GetNodeInventory reports what is actually on one server, live
	// from its agent: installed package versions and every program
	// (controller-managed or created node-locally via the in-container
	// CLI).
	GetNodeInventory(context.Context, *GetNodeInventoryRequest) (*NodeInventory, error)
	// GetNodeMetrics GetNodeMetrics samples resource usage of one server live from
	// its agent, node-exporter style: CPU, memory, load, filesystem,
	// disk I/O and per-interface network.
	GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*NodeMetrics, error)
	// GetNodeMetricsHistory GetNodeMetricsHistory returns the collected resource-usage time
	// series of one server: 15 s points from the controller's metrics
	// collector, kept 2 h in memory and 24 h on disk.
	GetNodeMetricsHistory(context.Context, *GetNodeMetricsHistoryRequest) (*NodeMetricsHistory, error)
	// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
	// one deployed node; routes are empty unless the container is
	// running.
	GetNodeRoutes(context.Context, *GetNodeRoutesRequest) (*NodeRoutes, error)
	// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
	// the underlying container state and every kernel interface inside
	// it, including implementation plumbing (bridge, VRRP macvlan,
	// management eth0) that the simulated topology does not model.
	GetNodeRuntime(context.Context, *GetNodeRuntimeRequest) (*NodeRuntime, error)
	// GetOperation --- Operations & Generations ---
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	GetPlan(context.Context, *GetPlanRequest) (*Plan, error)
	GetProgramLogs(context.Context, *GetProgramLogsRequest) (*ProgramLogs, error)
	Healthz(context.Context, *HealthzRequest) (*HealthzReply, error)
	// InstallPackage InstallPackage delivers a package version onto lab servers
	// without declaring a program — the "deploy a binary" path (apt
	// install without a service unit). Idempotent per server: agents
	// skip versions already present with the same digest.
	InstallPackage(context.Context, *InstallPackageRequest) (*InstallPackageReply, error)
	ListAllocations(context.Context, *ListAllocationsRequest) (*ListAllocationsReply, error)
	ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsReply, error)
	ListLabs(context.Context, *ListLabsRequest) (*ListLabsReply, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksReply, error)
	// ListNodes --- Topology ---
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsReply, error)
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesReply, error)
	// ListProfiles --- Profiles & health ---
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesReply, error)
	ListPrograms(context.Context, *ListProgramsRequest) (*ListProgramsReply, error)
	// StartLab StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(context.Context, *StartLabRequest) (*OperationRef, error)
	// StartNode StartNode / StopNode power a single device on and off.
	StartNode(context.Context, *StartNodeRequest) (*Node, error)
	StartProgram(context.Context, *ProgramOpRequest) (*Program, error)
	StopLab(context.Context, *StopLabRequest) (*OperationRef, error)
	StopNode(context.Context, *StopNodeRequest) (*Node, error)
	StopProgram(context.Context, *ProgramOpRequest) (*Program, error)
	UpgradeProgram(context.Context, *UpgradeProgramRequest) (*Program, error)
	// UploadPackage --- Packages ---
	// Packages are versioned program artifacts (tar.gz with a
	// manifest.json) in the controller's repository; lab servers
	// install them through their agent. The bundled lab-app registers
	// as the builtin package; uploads use the same pipeline.
	UploadPackage(context.Context, *UploadPackageRequest) (*Package, error)
}

func RegisterDCNetLabHTTPServer(s *http.Server, srv DCNetLabHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/labs", _DCNetLab_CreateLab0_HTTP_Handler(srv))
	r.GET("/api/v1/labs", _DCNetLab_ListLabs0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{id}", _DCNetLab_GetLab0_HTTP_Handler(srv))
	r.DELETE("/api/v1/labs/{id}", _DCNetLab_DeleteLab0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{id}/start", _DCNetLab_StartLab0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{id}/stop", _DCNetLab_StopLab0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes", _DCNetLab_ListNodes0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/links", _DCNetLab_ListLinks0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/allocations", _DCNetLab_ListAllocations0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/nodes/{node_id}/start", _DCNetLab_StartNode0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/nodes/{node_id}/stop", _DCNetLab_StopNode0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/runtime", _DCNetLab_GetNodeRuntime0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/bgp", _DCNetLab_GetNodeBGP0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/routes", _DCNetLab_GetNodeRoutes0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/bgp-table", _DCNetLab_GetNodeBGPTable0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/fib", _DCNetLab_GetNodeFIB0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/metrics", _DCNetLab_GetNodeMetrics0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/metrics/history", _DCNetLab_GetNodeMetricsHistory0_HTTP_Handler(srv))
	r.POST("/api/v1/packages", _DCNetLab_UploadPackage0_HTTP_Handler(srv))
	r.GET("/api/v1/packages", _DCNetLab_ListPackages0_HTTP_Handler(srv))
	r.DELETE("/api/v1/packages/{name}/{version}", _DCNetLab_DeletePackage0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/inventory", _DCNetLab_GetNodeInventory0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/packages/{name}/{version}/install", _DCNetLab_InstallPackage0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/programs", _DCNetLab_CreateProgram0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/programs", _DCNetLab_ListPrograms0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/programs/{id}/start", _DCNetLab_StartProgram0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/programs/{id}/stop", _DCNetLab_StopProgram0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/programs/{id}/upgrade", _DCNetLab_UpgradeProgram0_HTTP_Handler(srv))
	r.DELETE("/api/v1/labs/{lab_id}/programs/{id}", _DCNetLab_DeleteProgram0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/programs/{id}/logs", _DCNetLab_GetProgramLogs0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/plans", _DCNetLab_CreatePlan0_HTTP_Handler(srv))
	r.GET("/api/v1/plans/{id}", _DCNetLab_GetPlan0_HTTP_Handler(srv))
	r.POST("/api/v1/plans/{id}/apply", _DCNetLab_ApplyPlan0_HTTP_Handler(srv))
	r.GET("/api/v1/operations/{id}", _DCNetLab_GetOperation0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/operations", _DCNetLab_ListOperations0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/generations", _DCNetLab_ListGenerations0_HTTP_Handler(srv))
	r.GET("/api/v1/profiles", _DCNetLab_ListProfiles0_HTTP_Handler(srv))
	r.GET("/api/v1/healthz", _DCNetLab_Healthz0_HTTP_Handler(srv))
}

func _DCNetLab_CreateLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabCreateLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLab(ctx, req.(*CreateLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Lab)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListLabs0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLabsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListLabs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLabs(ctx, req.(*ListLabsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLabsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLabRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLab(ctx, req.(*GetLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Lab)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_DeleteLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteLabRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabDeleteLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteLab(ctx, req.(*DeleteLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StartLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStartLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLab(ctx, req.(*StartLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StopLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStopLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopLab(ctx, req.(*StopLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListNodes0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListNodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNodes(ctx, req.(*ListNodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNodesReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListLinks0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLinksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListLinks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLinks(ctx, req.(*ListLinksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLinksReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListAllocations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAllocationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListAllocations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAllocations(ctx, req.(*ListAllocationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAllocationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StartNode0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStartNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartNode(ctx, req.(*StartNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StopNode0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStopNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopNode(ctx, req.(*StopNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeRuntime0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRuntimeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeRuntime)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeRuntime(ctx, req.(*GetNodeRuntimeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeRuntime)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeBGP0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeBGPRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeBGP)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeBGP(ctx, req.(*GetNodeBGPRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeBGP)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeRoutes0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRoutesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeRoutes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeRoutes(ctx, req.(*GetNodeRoutesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeRoutes)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeBGPTable0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeBGPTableRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeBGPTable)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeBGPTable(ctx, req.(*GetNodeBGPTableRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeBGPTable)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeFIB0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeFIBRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeFIB)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeFIB(ctx, req.(*GetNodeFIBRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeFIB)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeMetrics0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeMetricsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeMetrics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeMetrics(ctx, req.(*GetNodeMetricsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeMetrics)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeMetricsHistory0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeMetricsHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeMetricsHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeMetricsHistory(ctx, req.(*GetNodeMetricsHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeMetricsHistory)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_UploadPackage0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabUploadPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadPackage(ctx, req.(*UploadPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Package)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListPackages0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPackagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListPackages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPackages(ctx, req.(*ListPackagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPackagesReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_DeletePackage0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePackageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabDeletePackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePackage(ctx, req.(*DeletePackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePackageReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeInventory0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeInventoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeInventory(ctx, req.(*GetNodeInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeInventory)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_InstallPackage0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InstallPackageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabInstallPackage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InstallPackage(ctx, req.(*InstallPackageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InstallPackageReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_CreateProgram0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProgramRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabCreateProgram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProgram(ctx, req.(*CreateProgramRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProgramReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListPrograms0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProgramsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListPrograms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPrograms(ctx, req.(*ListProgramsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProgramsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StartProgram0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProgramOpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStartProgram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartProgram(ctx, req.(*ProgramOpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Program)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StopProgram0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProgramOpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStopProgram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopProgram(ctx, req.(*ProgramOpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Program)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_UpgradeProgram0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpgradeProgramRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabUpgradeProgram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpgradeProgram(ctx, req.(*UpgradeProgramRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Program)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_DeleteProgram0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProgramOpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabDeleteProgram)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteProgram(ctx, req.(*ProgramOpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteProgramReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetProgramLogs0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProgramLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetProgramLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProgramLogs(ctx, req.(*GetProgramLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProgramLogs)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_CreatePlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabCreatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlan(ctx, req.(*CreatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Plan)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetPlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlan(ctx, req.(*GetPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Plan)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ApplyPlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabApplyPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyPlan(ctx, req.(*ApplyPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetOperation0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOperationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetOperation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOperation(ctx, req.(*GetOperationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Operation)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListOperations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOperationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListOperations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOperations(ctx, req.(*ListOperationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOperationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListGenerations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGenerationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListGenerations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGenerations(ctx, req.(*ListGenerationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGenerationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListProfiles0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProfilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListProfiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProfiles(ctx, req.(*ListProfilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProfilesReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_Healthz0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabHealthz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Healthz(ctx, req.(*HealthzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthzReply)
		return ctx.Result(200, reply)
	}
}

type DCNetLabHTTPClient interface {
	ApplyPlan(ctx context.Context, req *ApplyPlanRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	// CreateLab --- Labs ---
	CreateLab(ctx context.Context, req *CreateLabRequest, opts ...http.CallOption) (rsp *Lab, err error)
	// CreatePlan --- Plans ---
	CreatePlan(ctx context.Context, req *CreatePlanRequest, opts ...http.CallOption) (rsp *Plan, err error)
	// CreateProgram --- Programs ---
	// Programs are supervised processes on lab servers, each running
	// the entrypoint of an installed Package version, managed through
	// the per-server dcnetlab-server-agent.
	CreateProgram(ctx context.Context, req *CreateProgramRequest, opts ...http.CallOption) (rsp *CreateProgramReply, err error)
	DeleteLab(ctx context.Context, req *DeleteLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	DeletePackage(ctx context.Context, req *DeletePackageRequest, opts ...http.CallOption) (rsp *DeletePackageReply, err error)
	DeleteProgram(ctx context.Context, req *ProgramOpRequest, opts ...http.CallOption) (rsp *DeleteProgramReply, err error)
	GetLab(ctx context.Context, req *GetLabRequest, opts ...http.CallOption) (rsp *Lab, err error)
	// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
	// by the FRR compiler from the topology model: eBGP neighbors over
	// fabric links, the MLAG iBGP session and the leaf's dynamic server
	// peer-group. Empty for nodes that do not run BGP.
	GetNodeBGP(ctx context.Context, req *GetNodeBGPRequest, opts ...http.CallOption) (rsp *NodeBGP, err error)
	// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
	// node (`show ip bgp`): every candidate path per prefix, before
	// best-path selection reduces them to the RIB entry.
	GetNodeBGPTable(ctx context.Context, req *GetNodeBGPTableRequest, opts ...http.CallOption) (rsp *NodeBGPTable, err error)
	// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
	// deployed node (`ip route`): what actually forwards packets, as
	// installed by zebra from the RIB.
	GetNodeFIB(ctx context.Context, req *GetNodeFIBRequest, opts ...http.CallOption) (rsp *NodeFIB, err error)
	// GetNodeInventory GetNodeInventory reports what is actually on one server, live
	// from its agent: installed package versions and every program
	// (controller-managed or created node-locally via the in-container
	// CLI).
	GetNodeInventory(ctx context.Context, req *GetNodeInventoryRequest, opts ...http.CallOption) (rsp *NodeInventory, err error)
	// GetNodeMetrics GetNodeMetrics samples resource usage of one server live from
	// its agent, node-exporter style: CPU, memory, load, filesystem,
	// disk I/O and per-interface network.
	GetNodeMetrics(ctx context.Context, req *GetNodeMetricsRequest, opts ...http.CallOption) (rsp *NodeMetrics, err error)
	// GetNodeMetricsHistory GetNodeMetricsHistory returns the collected resource-usage time
	// series of one server: 15 s points from the controller's metrics
	// collector, kept 2 h in memory and 24 h on disk.
	GetNodeMetricsHistory(ctx context.Context, req *GetNodeMetricsHistoryRequest, opts ...http.CallOption) (rsp *NodeMetricsHistory, err error)
	// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
	// one deployed node; routes are empty unless the container is
	// running.
	GetNodeRoutes(ctx context.Context, req *GetNodeRoutesRequest, opts ...http.CallOption) (rsp *NodeRoutes, err error)
	// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
	// the underlying container state and every kernel interface inside
	// it, including implementation plumbing (bridge, VRRP macvlan,
	// management eth0) that the simulated topology does not model.
	GetNodeRuntime(ctx context.Context, req *GetNodeRuntimeRequest, opts ...http.CallOption) (rsp *NodeRuntime, err error)
	// GetOperation --- Operations & Generations ---
	GetOperation(ctx context.Context, req *GetOperationRequest, opts ...http.CallOption) (rsp *Operation, err error)
	GetPlan(ctx context.Context, req *GetPlanRequest, opts ...http.CallOption) (rsp *Plan, err error)
	GetProgramLogs(ctx context.Context, req *GetProgramLogsRequest, opts ...http.CallOption) (rsp *ProgramLogs, err error)
	Healthz(ctx context.Context, req *HealthzRequest, opts ...http.CallOption) (rsp *HealthzReply, err error)
	// InstallPackage InstallPackage delivers a package version onto lab servers
	// without declaring a program — the "deploy a binary" path (apt
	// install without a service unit). Idempotent per server: agents
	// skip versions already present with the same digest.
	InstallPackage(ctx context.Context, req *InstallPackageRequest, opts ...http.CallOption) (rsp *InstallPackageReply, err error)
	ListAllocations(ctx context.Context, req *ListAllocationsRequest, opts ...http.CallOption) (rsp *ListAllocationsReply, err error)
	ListGenerations(ctx context.Context, req *ListGenerationsRequest, opts ...http.CallOption) (rsp *ListGenerationsReply, err error)
	ListLabs(ctx context.Context, req *ListLabsRequest, opts ...http.CallOption) (rsp *ListLabsReply, err error)
	ListLinks(ctx context.Context, req *ListLinksRequest, opts ...http.CallOption) (rsp *ListLinksReply, err error)
	// ListNodes --- Topology ---
	ListNodes(ctx context.Context, req *ListNodesRequest, opts ...http.CallOption) (rsp *ListNodesReply, err error)
	ListOperations(ctx context.Context, req *ListOperationsRequest, opts ...http.CallOption) (rsp *ListOperationsReply, err error)
	ListPackages(ctx context.Context, req *ListPackagesRequest, opts ...http.CallOption) (rsp *ListPackagesReply, err error)
	// ListProfiles --- Profiles & health ---
	ListProfiles(ctx context.Context, req *ListProfilesRequest, opts ...http.CallOption) (rsp *ListProfilesReply, err error)
	ListPrograms(ctx context.Context, req *ListProgramsRequest, opts ...http.CallOption) (rsp *ListProgramsReply, err error)
	// StartLab StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(ctx context.Context, req *StartLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	// StartNode StartNode / StopNode power a single device on and off.
	StartNode(ctx context.Context, req *StartNodeRequest, opts ...http.CallOption) (rsp *Node, err error)
	StartProgram(ctx context.Context, req *ProgramOpRequest, opts ...http.CallOption) (rsp *Program, err error)
	StopLab(ctx context.Context, req *StopLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	StopNode(ctx context.Context, req *StopNodeRequest, opts ...http.CallOption) (rsp *Node, err error)
	StopProgram(ctx context.Context, req *ProgramOpRequest, opts ...http.CallOption) (rsp *Program, err error)
	UpgradeProgram(ctx context.Context, req *UpgradeProgramRequest, opts ...http.CallOption) (rsp *Program, err error)
	// UploadPackage --- Packages ---
	// Packages are versioned program artifacts (tar.gz with a
	// manifest.json) in the controller's repository; lab servers
	// install them through their agent. The bundled lab-app registers
	// as the builtin package; uploads use the same pipeline.
	UploadPackage(ctx context.Context, req *UploadPackageRequest, opts ...http.CallOption) (rsp *Package, err error)
}

type DCNetLabHTTPClientImpl struct {
	cc *http.Client
}

func NewDCNetLabHTTPClient(client *http.Client) DCNetLabHTTPClient {
	return &DCNetLabHTTPClientImpl{client}
}

func (c *DCNetLabHTTPClientImpl) ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/plans/{id}/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabApplyPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLab --- Labs ---
func (c *DCNetLabHTTPClientImpl) CreateLab(ctx context.Context, in *CreateLabRequest, opts ...http.CallOption) (*Lab, error) {
	var out Lab
	pattern := "/api/v1/labs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabCreateLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePlan --- Plans ---
func (c *DCNetLabHTTPClientImpl) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...http.CallOption) (*Plan, error) {
	var out Plan
	pattern := "/api/v1/labs/{lab_id}/plans"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabCreatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateProgram --- Programs ---
// Programs are supervised processes on lab servers, each running
// the entrypoint of an installed Package version, managed through
// the per-server dcnetlab-server-agent.
func (c *DCNetLabHTTPClientImpl) CreateProgram(ctx context.Context, in *CreateProgramRequest, opts ...http.CallOption) (*CreateProgramReply, error) {
	var out CreateProgramReply
	pattern := "/api/v1/labs/{lab_id}/programs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabCreateProgram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) DeleteLab(ctx context.Context, in *DeleteLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabDeleteLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) DeletePackage(ctx context.Context, in *DeletePackageRequest, opts ...http.CallOption) (*DeletePackageReply, error) {
	var out DeletePackageReply
	pattern := "/api/v1/packages/{name}/{version}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabDeletePackage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) DeleteProgram(ctx context.Context, in *ProgramOpRequest, opts ...http.CallOption) (*DeleteProgramReply, error) {
	var out DeleteProgramReply
	pattern := "/api/v1/labs/{lab_id}/programs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabDeleteProgram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) GetLab(ctx context.Context, in *GetLabRequest, opts ...http.CallOption) (*Lab, error) {
	var out Lab
	pattern := "/api/v1/labs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
// by the FRR compiler from the topology model: eBGP neighbors over
// fabric links, the MLAG iBGP session and the leaf's dynamic server
// peer-group. Empty for nodes that do not run BGP.
func (c *DCNetLabHTTPClientImpl) GetNodeBGP(ctx context.Context, in *GetNodeBGPRequest, opts ...http.CallOption) (*NodeBGP, error) {
	var out NodeBGP
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/bgp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeBGP))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
// node (`show ip bgp`): every candidate path per prefix, before
// best-path selection reduces them to the RIB entry.
func (c *DCNetLabHTTPClientImpl) GetNodeBGPTable(ctx context.Context, in *GetNodeBGPTableRequest, opts ...http.CallOption) (*NodeBGPTable, error) {
	var out NodeBGPTable
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/bgp-table"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeBGPTable))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
// deployed node (`ip route`): what actually forwards packets, as
// installed by zebra from the RIB.
func (c *DCNetLabHTTPClientImpl) GetNodeFIB(ctx context.Context, in *GetNodeFIBRequest, opts ...http.CallOption) (*NodeFIB, error) {
	var out NodeFIB
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/fib"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeFIB))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeInventory GetNodeInventory reports what is actually on one server, live
// from its agent: installed package versions and every program
// (controller-managed or created node-locally via the in-container
// CLI).
func (c *DCNetLabHTTPClientImpl) GetNodeInventory(ctx context.Context, in *GetNodeInventoryRequest, opts ...http.CallOption) (*NodeInventory, error) {
	var out NodeInventory
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/inventory"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeMetrics GetNodeMetrics samples resource usage of one server live from
// its agent, node-exporter style: CPU, memory, load, filesystem,
// disk I/O and per-interface network.
func (c *DCNetLabHTTPClientImpl) GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...http.CallOption) (*NodeMetrics, error) {
	var out NodeMetrics
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/metrics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeMetrics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeMetricsHistory GetNodeMetricsHistory returns the collected resource-usage time
// series of one server: 15 s points from the controller's metrics
// collector, kept 2 h in memory and 24 h on disk.
func (c *DCNetLabHTTPClientImpl) GetNodeMetricsHistory(ctx context.Context, in *GetNodeMetricsHistoryRequest, opts ...http.CallOption) (*NodeMetricsHistory, error) {
	var out NodeMetricsHistory
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/metrics/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeMetricsHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
// one deployed node; routes are empty unless the container is
// running.
func (c *DCNetLabHTTPClientImpl) GetNodeRoutes(ctx context.Context, in *GetNodeRoutesRequest, opts ...http.CallOption) (*NodeRoutes, error) {
	var out NodeRoutes
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/routes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeRoutes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
// the underlying container state and every kernel interface inside
// it, including implementation plumbing (bridge, VRRP macvlan,
// management eth0) that the simulated topology does not model.
func (c *DCNetLabHTTPClientImpl) GetNodeRuntime(ctx context.Context, in *GetNodeRuntimeRequest, opts ...http.CallOption) (*NodeRuntime, error) {
	var out NodeRuntime
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/runtime"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeRuntime))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOperation --- Operations & Generations ---
func (c *DCNetLabHTTPClientImpl) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...http.CallOption) (*Operation, error) {
	var out Operation
	pattern := "/api/v1/operations/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetOperation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...http.CallOption) (*Plan, error) {
	var out Plan
	pattern := "/api/v1/plans/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) GetProgramLogs(ctx context.Context, in *GetProgramLogsRequest, opts ...http.CallOption) (*ProgramLogs, error) {
	var out ProgramLogs
	pattern := "/api/v1/labs/{lab_id}/programs/{id}/logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetProgramLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) Healthz(ctx context.Context, in *HealthzRequest, opts ...http.CallOption) (*HealthzReply, error) {
	var out HealthzReply
	pattern := "/api/v1/healthz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabHealthz))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InstallPackage InstallPackage delivers a package version onto lab servers
// without declaring a program — the "deploy a binary" path (apt
// install without a service unit). Idempotent per server: agents
// skip versions already present with the same digest.
func (c *DCNetLabHTTPClientImpl) InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...http.CallOption) (*InstallPackageReply, error) {
	var out InstallPackageReply
	pattern := "/api/v1/labs/{lab_id}/packages/{name}/{version}/install"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabInstallPackage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...http.CallOption) (*ListAllocationsReply, error) {
	var out ListAllocationsReply
	pattern := "/api/v1/labs/{lab_id}/allocations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListAllocations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...http.CallOption) (*ListGenerationsReply, error) {
	var out ListGenerationsReply
	pattern := "/api/v1/labs/{lab_id}/generations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListGenerations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListLabs(ctx context.Context, in *ListLabsRequest, opts ...http.CallOption) (*ListLabsReply, error) {
	var out ListLabsReply
	pattern := "/api/v1/labs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListLabs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...http.CallOption) (*ListLinksReply, error) {
	var out ListLinksReply
	pattern := "/api/v1/labs/{lab_id}/links"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListLinks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNodes --- Topology ---
func (c *DCNetLabHTTPClientImpl) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...http.CallOption) (*ListNodesReply, error) {
	var out ListNodesReply
	pattern := "/api/v1/labs/{lab_id}/nodes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListNodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...http.CallOption) (*ListOperationsReply, error) {
	var out ListOperationsReply
	pattern := "/api/v1/labs/{lab_id}/operations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListOperations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...http.CallOption) (*ListPackagesReply, error) {
	var out ListPackagesReply
	pattern := "/api/v1/packages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListPackages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProfiles --- Profiles & health ---
func (c *DCNetLabHTTPClientImpl) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...http.CallOption) (*ListProfilesReply, error) {
	var out ListProfilesReply
	pattern := "/api/v1/profiles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListProfiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListPrograms(ctx context.Context, in *ListProgramsRequest, opts ...http.CallOption) (*ListProgramsReply, error) {
	var out ListProgramsReply
	pattern := "/api/v1/labs/{lab_id}/programs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListPrograms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartLab StartLab / StopLab power the deployed containers of a lab on and
// off (docker start/stop) without touching the generation.
func (c *DCNetLabHTTPClientImpl) StartLab(ctx context.Context, in *StartLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStartLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartNode StartNode / StopNode power a single device on and off.
func (c *DCNetLabHTTPClientImpl) StartNode(ctx context.Context, in *StartNodeRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStartNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StartProgram(ctx context.Context, in *ProgramOpRequest, opts ...http.CallOption) (*Program, error) {
	var out Program
	pattern := "/api/v1/labs/{lab_id}/programs/{id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStartProgram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StopLab(ctx context.Context, in *StopLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStopLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StopNode(ctx context.Context, in *StopNodeRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStopNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StopProgram(ctx context.Context, in *ProgramOpRequest, opts ...http.CallOption) (*Program, error) {
	var out Program
	pattern := "/api/v1/labs/{lab_id}/programs/{id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStopProgram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) UpgradeProgram(ctx context.Context, in *UpgradeProgramRequest, opts ...http.CallOption) (*Program, error) {
	var out Program
	pattern := "/api/v1/labs/{lab_id}/programs/{id}/upgrade"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabUpgradeProgram))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadPackage --- Packages ---
// Packages are versioned program artifacts (tar.gz with a
// manifest.json) in the controller's repository; lab servers
// install them through their agent. The bundled lab-app registers
// as the builtin package; uploads use the same pipeline.
func (c *DCNetLabHTTPClientImpl) UploadPackage(ctx context.Context, in *UploadPackageRequest, opts ...http.CallOption) (*Package, error) {
	var out Package
	pattern := "/api/v1/packages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabUploadPackage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
