// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: dcnetlab/v1/dcnetlab.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDCNetLabApplyPlan = "/dcnetlab.v1.DCNetLab/ApplyPlan"
const OperationDCNetLabCreateLab = "/dcnetlab.v1.DCNetLab/CreateLab"
const OperationDCNetLabCreatePlan = "/dcnetlab.v1.DCNetLab/CreatePlan"
const OperationDCNetLabDeleteLab = "/dcnetlab.v1.DCNetLab/DeleteLab"
const OperationDCNetLabGetLab = "/dcnetlab.v1.DCNetLab/GetLab"
const OperationDCNetLabGetNodeBGP = "/dcnetlab.v1.DCNetLab/GetNodeBGP"
const OperationDCNetLabGetNodeBGPTable = "/dcnetlab.v1.DCNetLab/GetNodeBGPTable"
const OperationDCNetLabGetNodeFIB = "/dcnetlab.v1.DCNetLab/GetNodeFIB"
const OperationDCNetLabGetNodeRoutes = "/dcnetlab.v1.DCNetLab/GetNodeRoutes"
const OperationDCNetLabGetNodeRuntime = "/dcnetlab.v1.DCNetLab/GetNodeRuntime"
const OperationDCNetLabGetOperation = "/dcnetlab.v1.DCNetLab/GetOperation"
const OperationDCNetLabGetPlan = "/dcnetlab.v1.DCNetLab/GetPlan"
const OperationDCNetLabHealthz = "/dcnetlab.v1.DCNetLab/Healthz"
const OperationDCNetLabListAllocations = "/dcnetlab.v1.DCNetLab/ListAllocations"
const OperationDCNetLabListGenerations = "/dcnetlab.v1.DCNetLab/ListGenerations"
const OperationDCNetLabListLabs = "/dcnetlab.v1.DCNetLab/ListLabs"
const OperationDCNetLabListLinks = "/dcnetlab.v1.DCNetLab/ListLinks"
const OperationDCNetLabListNodes = "/dcnetlab.v1.DCNetLab/ListNodes"
const OperationDCNetLabListOperations = "/dcnetlab.v1.DCNetLab/ListOperations"
const OperationDCNetLabListProfiles = "/dcnetlab.v1.DCNetLab/ListProfiles"
const OperationDCNetLabStartLab = "/dcnetlab.v1.DCNetLab/StartLab"
const OperationDCNetLabStartNode = "/dcnetlab.v1.DCNetLab/StartNode"
const OperationDCNetLabStopLab = "/dcnetlab.v1.DCNetLab/StopLab"
const OperationDCNetLabStopNode = "/dcnetlab.v1.DCNetLab/StopNode"

type DCNetLabHTTPServer interface {
	ApplyPlan(context.Context, *ApplyPlanRequest) (*OperationRef, error)
	// CreateLab --- Labs ---
	CreateLab(context.Context, *CreateLabRequest) (*Lab, error)
	// CreatePlan --- Plans ---
	CreatePlan(context.Context, *CreatePlanRequest) (*Plan, error)
	DeleteLab(context.Context, *DeleteLabRequest) (*OperationRef, error)
	GetLab(context.Context, *GetLabRequest) (*Lab, error)
	// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
	// by the FRR compiler from the topology model: eBGP neighbors over
	// fabric links, the MLAG iBGP session and the leaf's dynamic server
	// peer-group. Empty for nodes that do not run BGP.
	GetNodeBGP(context.Context, *GetNodeBGPRequest) (*NodeBGP, error)
	// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
	// node (`show ip bgp`): every candidate path per prefix, before
	// best-path selection reduces them to the RIB entry.
	GetNodeBGPTable(context.Context, *GetNodeBGPTableRequest) (*NodeBGPTable, error)
	// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
	// deployed node (`ip route`): what actually forwards packets, as
	// installed by zebra from the RIB.
	GetNodeFIB(context.Context, *GetNodeFIBRequest) (*NodeFIB, error)
	// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
	// one deployed node; routes are empty unless the container is
	// running.
	GetNodeRoutes(context.Context, *GetNodeRoutesRequest) (*NodeRoutes, error)
	// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
	// the underlying container state and every kernel interface inside
	// it, including implementation plumbing (bridge, VRRP macvlan,
	// management eth0) that the simulated topology does not model.
	GetNodeRuntime(context.Context, *GetNodeRuntimeRequest) (*NodeRuntime, error)
	// GetOperation --- Operations & Generations ---
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	GetPlan(context.Context, *GetPlanRequest) (*Plan, error)
	Healthz(context.Context, *HealthzRequest) (*HealthzReply, error)
	ListAllocations(context.Context, *ListAllocationsRequest) (*ListAllocationsReply, error)
	ListGenerations(context.Context, *ListGenerationsRequest) (*ListGenerationsReply, error)
	ListLabs(context.Context, *ListLabsRequest) (*ListLabsReply, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksReply, error)
	// ListNodes --- Topology ---
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesReply, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsReply, error)
	// ListProfiles --- Profiles & health ---
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesReply, error)
	// StartLab StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(context.Context, *StartLabRequest) (*OperationRef, error)
	// StartNode StartNode / StopNode power a single device on and off.
	StartNode(context.Context, *StartNodeRequest) (*Node, error)
	StopLab(context.Context, *StopLabRequest) (*OperationRef, error)
	StopNode(context.Context, *StopNodeRequest) (*Node, error)
}

func RegisterDCNetLabHTTPServer(s *http.Server, srv DCNetLabHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/labs", _DCNetLab_CreateLab0_HTTP_Handler(srv))
	r.GET("/api/v1/labs", _DCNetLab_ListLabs0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{id}", _DCNetLab_GetLab0_HTTP_Handler(srv))
	r.DELETE("/api/v1/labs/{id}", _DCNetLab_DeleteLab0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{id}/start", _DCNetLab_StartLab0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{id}/stop", _DCNetLab_StopLab0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes", _DCNetLab_ListNodes0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/links", _DCNetLab_ListLinks0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/allocations", _DCNetLab_ListAllocations0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/nodes/{node_id}/start", _DCNetLab_StartNode0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/nodes/{node_id}/stop", _DCNetLab_StopNode0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/runtime", _DCNetLab_GetNodeRuntime0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/bgp", _DCNetLab_GetNodeBGP0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/routes", _DCNetLab_GetNodeRoutes0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/bgp-table", _DCNetLab_GetNodeBGPTable0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/nodes/{node_id}/fib", _DCNetLab_GetNodeFIB0_HTTP_Handler(srv))
	r.POST("/api/v1/labs/{lab_id}/plans", _DCNetLab_CreatePlan0_HTTP_Handler(srv))
	r.GET("/api/v1/plans/{id}", _DCNetLab_GetPlan0_HTTP_Handler(srv))
	r.POST("/api/v1/plans/{id}/apply", _DCNetLab_ApplyPlan0_HTTP_Handler(srv))
	r.GET("/api/v1/operations/{id}", _DCNetLab_GetOperation0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/operations", _DCNetLab_ListOperations0_HTTP_Handler(srv))
	r.GET("/api/v1/labs/{lab_id}/generations", _DCNetLab_ListGenerations0_HTTP_Handler(srv))
	r.GET("/api/v1/profiles", _DCNetLab_ListProfiles0_HTTP_Handler(srv))
	r.GET("/api/v1/healthz", _DCNetLab_Healthz0_HTTP_Handler(srv))
}

func _DCNetLab_CreateLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabCreateLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateLab(ctx, req.(*CreateLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Lab)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListLabs0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLabsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListLabs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLabs(ctx, req.(*ListLabsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLabsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLabRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLab(ctx, req.(*GetLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Lab)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_DeleteLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteLabRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabDeleteLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteLab(ctx, req.(*DeleteLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StartLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStartLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartLab(ctx, req.(*StartLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StopLab0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopLabRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStopLab)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopLab(ctx, req.(*StopLabRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListNodes0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListNodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNodes(ctx, req.(*ListNodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNodesReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListLinks0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListLinksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListLinks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListLinks(ctx, req.(*ListLinksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListLinksReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListAllocations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAllocationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListAllocations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAllocations(ctx, req.(*ListAllocationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAllocationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StartNode0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStartNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartNode(ctx, req.(*StartNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_StopNode0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopNodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabStopNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopNode(ctx, req.(*StopNodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Node)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeRuntime0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRuntimeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeRuntime)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeRuntime(ctx, req.(*GetNodeRuntimeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeRuntime)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeBGP0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeBGPRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeBGP)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeBGP(ctx, req.(*GetNodeBGPRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeBGP)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeRoutes0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeRoutesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeRoutes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeRoutes(ctx, req.(*GetNodeRoutesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeRoutes)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeBGPTable0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeBGPTableRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeBGPTable)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeBGPTable(ctx, req.(*GetNodeBGPTableRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeBGPTable)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetNodeFIB0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeFIBRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetNodeFIB)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNodeFIB(ctx, req.(*GetNodeFIBRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeFIB)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_CreatePlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabCreatePlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePlan(ctx, req.(*CreatePlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Plan)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetPlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPlan(ctx, req.(*GetPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Plan)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ApplyPlan0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabApplyPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyPlan(ctx, req.(*ApplyPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OperationRef)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_GetOperation0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOperationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabGetOperation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOperation(ctx, req.(*GetOperationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Operation)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListOperations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOperationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListOperations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOperations(ctx, req.(*ListOperationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOperationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListGenerations0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGenerationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListGenerations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGenerations(ctx, req.(*ListGenerationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGenerationsReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_ListProfiles0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProfilesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabListProfiles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProfiles(ctx, req.(*ListProfilesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProfilesReply)
		return ctx.Result(200, reply)
	}
}

func _DCNetLab_Healthz0_HTTP_Handler(srv DCNetLabHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDCNetLabHealthz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Healthz(ctx, req.(*HealthzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthzReply)
		return ctx.Result(200, reply)
	}
}

type DCNetLabHTTPClient interface {
	ApplyPlan(ctx context.Context, req *ApplyPlanRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	// CreateLab --- Labs ---
	CreateLab(ctx context.Context, req *CreateLabRequest, opts ...http.CallOption) (rsp *Lab, err error)
	// CreatePlan --- Plans ---
	CreatePlan(ctx context.Context, req *CreatePlanRequest, opts ...http.CallOption) (rsp *Plan, err error)
	DeleteLab(ctx context.Context, req *DeleteLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	GetLab(ctx context.Context, req *GetLabRequest, opts ...http.CallOption) (rsp *Lab, err error)
	// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
	// by the FRR compiler from the topology model: eBGP neighbors over
	// fabric links, the MLAG iBGP session and the leaf's dynamic server
	// peer-group. Empty for nodes that do not run BGP.
	GetNodeBGP(ctx context.Context, req *GetNodeBGPRequest, opts ...http.CallOption) (rsp *NodeBGP, err error)
	// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
	// node (`show ip bgp`): every candidate path per prefix, before
	// best-path selection reduces them to the RIB entry.
	GetNodeBGPTable(ctx context.Context, req *GetNodeBGPTableRequest, opts ...http.CallOption) (rsp *NodeBGPTable, err error)
	// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
	// deployed node (`ip route`): what actually forwards packets, as
	// installed by zebra from the RIB.
	GetNodeFIB(ctx context.Context, req *GetNodeFIBRequest, opts ...http.CallOption) (rsp *NodeFIB, err error)
	// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
	// one deployed node; routes are empty unless the container is
	// running.
	GetNodeRoutes(ctx context.Context, req *GetNodeRoutesRequest, opts ...http.CallOption) (rsp *NodeRoutes, err error)
	// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
	// the underlying container state and every kernel interface inside
	// it, including implementation plumbing (bridge, VRRP macvlan,
	// management eth0) that the simulated topology does not model.
	GetNodeRuntime(ctx context.Context, req *GetNodeRuntimeRequest, opts ...http.CallOption) (rsp *NodeRuntime, err error)
	// GetOperation --- Operations & Generations ---
	GetOperation(ctx context.Context, req *GetOperationRequest, opts ...http.CallOption) (rsp *Operation, err error)
	GetPlan(ctx context.Context, req *GetPlanRequest, opts ...http.CallOption) (rsp *Plan, err error)
	Healthz(ctx context.Context, req *HealthzRequest, opts ...http.CallOption) (rsp *HealthzReply, err error)
	ListAllocations(ctx context.Context, req *ListAllocationsRequest, opts ...http.CallOption) (rsp *ListAllocationsReply, err error)
	ListGenerations(ctx context.Context, req *ListGenerationsRequest, opts ...http.CallOption) (rsp *ListGenerationsReply, err error)
	ListLabs(ctx context.Context, req *ListLabsRequest, opts ...http.CallOption) (rsp *ListLabsReply, err error)
	ListLinks(ctx context.Context, req *ListLinksRequest, opts ...http.CallOption) (rsp *ListLinksReply, err error)
	// ListNodes --- Topology ---
	ListNodes(ctx context.Context, req *ListNodesRequest, opts ...http.CallOption) (rsp *ListNodesReply, err error)
	ListOperations(ctx context.Context, req *ListOperationsRequest, opts ...http.CallOption) (rsp *ListOperationsReply, err error)
	// ListProfiles --- Profiles & health ---
	ListProfiles(ctx context.Context, req *ListProfilesRequest, opts ...http.CallOption) (rsp *ListProfilesReply, err error)
	// StartLab StartLab / StopLab power the deployed containers of a lab on and
	// off (docker start/stop) without touching the generation.
	StartLab(ctx context.Context, req *StartLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	// StartNode StartNode / StopNode power a single device on and off.
	StartNode(ctx context.Context, req *StartNodeRequest, opts ...http.CallOption) (rsp *Node, err error)
	StopLab(ctx context.Context, req *StopLabRequest, opts ...http.CallOption) (rsp *OperationRef, err error)
	StopNode(ctx context.Context, req *StopNodeRequest, opts ...http.CallOption) (rsp *Node, err error)
}

type DCNetLabHTTPClientImpl struct {
	cc *http.Client
}

func NewDCNetLabHTTPClient(client *http.Client) DCNetLabHTTPClient {
	return &DCNetLabHTTPClientImpl{client}
}

func (c *DCNetLabHTTPClientImpl) ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/plans/{id}/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabApplyPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateLab --- Labs ---
func (c *DCNetLabHTTPClientImpl) CreateLab(ctx context.Context, in *CreateLabRequest, opts ...http.CallOption) (*Lab, error) {
	var out Lab
	pattern := "/api/v1/labs"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabCreateLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreatePlan --- Plans ---
func (c *DCNetLabHTTPClientImpl) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...http.CallOption) (*Plan, error) {
	var out Plan
	pattern := "/api/v1/labs/{lab_id}/plans"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabCreatePlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) DeleteLab(ctx context.Context, in *DeleteLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabDeleteLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) GetLab(ctx context.Context, in *GetLabRequest, opts ...http.CallOption) (*Lab, error) {
	var out Lab
	pattern := "/api/v1/labs/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeBGP GetNodeBGP returns the BGP configuration of one node as derived
// by the FRR compiler from the topology model: eBGP neighbors over
// fabric links, the MLAG iBGP session and the leaf's dynamic server
// peer-group. Empty for nodes that do not run BGP.
func (c *DCNetLabHTTPClientImpl) GetNodeBGP(ctx context.Context, in *GetNodeBGPRequest, opts ...http.CallOption) (*NodeBGP, error) {
	var out NodeBGP
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/bgp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeBGP))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeBGPTable GetNodeBGPTable returns the live BGP Loc-RIB of one deployed
// node (`show ip bgp`): every candidate path per prefix, before
// best-path selection reduces them to the RIB entry.
func (c *DCNetLabHTTPClientImpl) GetNodeBGPTable(ctx context.Context, in *GetNodeBGPTableRequest, opts ...http.CallOption) (*NodeBGPTable, error) {
	var out NodeBGPTable
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/bgp-table"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeBGPTable))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeFIB GetNodeFIB returns the live kernel forwarding table of one
// deployed node (`ip route`): what actually forwards packets, as
// installed by zebra from the RIB.
func (c *DCNetLabHTTPClientImpl) GetNodeFIB(ctx context.Context, in *GetNodeFIBRequest, opts ...http.CallOption) (*NodeFIB, error) {
	var out NodeFIB
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/fib"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeFIB))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeRoutes GetNodeRoutes returns the live IPv4 routing table (FRR RIB) of
// one deployed node; routes are empty unless the container is
// running.
func (c *DCNetLabHTTPClientImpl) GetNodeRoutes(ctx context.Context, in *GetNodeRoutesRequest, opts ...http.CallOption) (*NodeRoutes, error) {
	var out NodeRoutes
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/routes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeRoutes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNodeRuntime GetNodeRuntime returns the management view of one deployed node:
// the underlying container state and every kernel interface inside
// it, including implementation plumbing (bridge, VRRP macvlan,
// management eth0) that the simulated topology does not model.
func (c *DCNetLabHTTPClientImpl) GetNodeRuntime(ctx context.Context, in *GetNodeRuntimeRequest, opts ...http.CallOption) (*NodeRuntime, error) {
	var out NodeRuntime
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/runtime"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetNodeRuntime))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetOperation --- Operations & Generations ---
func (c *DCNetLabHTTPClientImpl) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...http.CallOption) (*Operation, error) {
	var out Operation
	pattern := "/api/v1/operations/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetOperation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) GetPlan(ctx context.Context, in *GetPlanRequest, opts ...http.CallOption) (*Plan, error) {
	var out Plan
	pattern := "/api/v1/plans/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabGetPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) Healthz(ctx context.Context, in *HealthzRequest, opts ...http.CallOption) (*HealthzReply, error) {
	var out HealthzReply
	pattern := "/api/v1/healthz"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabHealthz))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListAllocations(ctx context.Context, in *ListAllocationsRequest, opts ...http.CallOption) (*ListAllocationsReply, error) {
	var out ListAllocationsReply
	pattern := "/api/v1/labs/{lab_id}/allocations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListAllocations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListGenerations(ctx context.Context, in *ListGenerationsRequest, opts ...http.CallOption) (*ListGenerationsReply, error) {
	var out ListGenerationsReply
	pattern := "/api/v1/labs/{lab_id}/generations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListGenerations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListLabs(ctx context.Context, in *ListLabsRequest, opts ...http.CallOption) (*ListLabsReply, error) {
	var out ListLabsReply
	pattern := "/api/v1/labs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListLabs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...http.CallOption) (*ListLinksReply, error) {
	var out ListLinksReply
	pattern := "/api/v1/labs/{lab_id}/links"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListLinks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNodes --- Topology ---
func (c *DCNetLabHTTPClientImpl) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...http.CallOption) (*ListNodesReply, error) {
	var out ListNodesReply
	pattern := "/api/v1/labs/{lab_id}/nodes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListNodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...http.CallOption) (*ListOperationsReply, error) {
	var out ListOperationsReply
	pattern := "/api/v1/labs/{lab_id}/operations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListOperations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProfiles --- Profiles & health ---
func (c *DCNetLabHTTPClientImpl) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...http.CallOption) (*ListProfilesReply, error) {
	var out ListProfilesReply
	pattern := "/api/v1/profiles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDCNetLabListProfiles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartLab StartLab / StopLab power the deployed containers of a lab on and
// off (docker start/stop) without touching the generation.
func (c *DCNetLabHTTPClientImpl) StartLab(ctx context.Context, in *StartLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStartLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartNode StartNode / StopNode power a single device on and off.
func (c *DCNetLabHTTPClientImpl) StartNode(ctx context.Context, in *StartNodeRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStartNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StopLab(ctx context.Context, in *StopLabRequest, opts ...http.CallOption) (*OperationRef, error) {
	var out OperationRef
	pattern := "/api/v1/labs/{id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStopLab))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DCNetLabHTTPClientImpl) StopNode(ctx context.Context, in *StopNodeRequest, opts ...http.CallOption) (*Node, error) {
	var out Node
	pattern := "/api/v1/labs/{lab_id}/nodes/{node_id}/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDCNetLabStopNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
