// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/ifantsai/dcnetlab/controller/internal/biz"
	"github.com/ifantsai/dcnetlab/controller/internal/conf"
	"github.com/ifantsai/dcnetlab/controller/internal/data"
	"github.com/ifantsai/dcnetlab/controller/internal/metrics"
	"github.com/ifantsai/dcnetlab/controller/internal/observer"
	"github.com/ifantsai/dcnetlab/controller/internal/server"
	"github.com/ifantsai/dcnetlab/controller/internal/service"
	"github.com/ifantsai/dcnetlab/controller/internal/traffic"
)

// Injectors from wire.go:

// wireApp builds the controller object graph from the per-layer
// ProviderSets. Regenerate wire_gen.go with `make wire`.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, slogLogger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	labRepo := data.NewLabRepo(dataData)
	store := data.NewOperationStore(dataData)
	manager := biz.NewOperationManager(store, slogLogger)
	driver, cleanup2, err := data.NewRuntimeDriver(confData, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	labUsecase := biz.NewLabUsecase(labRepo, manager, driver, confData, slogLogger)
	topologyRepo := data.NewTopologyRepo(dataData)
	topologyUsecase := biz.NewTopologyUsecase(topologyRepo, slogLogger)
	planRepo := data.NewPlanRepo(dataData)
	programRepo := data.NewProgramRepo(dataData)
	programAgent := data.NewProgramAgent(driver, slogLogger)
	packageRepo := data.NewPackageRepo(dataData)
	packageUsecase, err := biz.NewPackageUsecase(packageRepo, confData, slogLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	history := metrics.NewHistory(confData, slogLogger)
	programUsecase := biz.NewProgramUsecase(programRepo, programAgent, driver, packageUsecase, history, confServer, slogLogger)
	planUsecase := biz.NewPlanUsecase(planRepo, manager, driver, programUsecase, confData, slogLogger)
	operationRepo := data.NewOperationRepo(dataData)
	operationUsecase := biz.NewOperationUsecase(operationRepo, slogLogger)
	powerRepo := data.NewPowerRepo(dataData)
	powerUsecase := biz.NewPowerUsecase(powerRepo, manager, driver, slogLogger)
	runtimeUsecase := biz.NewRuntimeUsecase(labRepo, topologyRepo, driver, slogLogger)
	trafficRepo := data.NewTrafficRepo(dataData)
	trafficHistory := traffic.NewHistory()
	trafficUsecase := biz.NewTrafficUsecase(trafficRepo, programUsecase, trafficHistory, slogLogger)
	faultRepo := data.NewFaultRepo(dataData)
	faultUsecase := biz.NewFaultUsecase(faultRepo, powerUsecase, driver, slogLogger)
	captureRepo := data.NewCaptureRepo(dataData)
	captureManager := biz.NewCaptureManager(driver, confData, slogLogger)
	captureUsecase, err := biz.NewCaptureUsecase(captureRepo, captureManager, slogLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dcNetLabService := service.NewDCNetLabService(labUsecase, topologyUsecase, planUsecase, operationUsecase, powerUsecase, runtimeUsecase, programUsecase, packageUsecase, trafficUsecase, faultUsecase, captureUsecase, slogLogger)
	terminalUsecase := biz.NewTerminalUsecase(labRepo, topologyRepo, driver, slogLogger)
	observerStore := data.NewObserverStore(dataData)
	observerObserver := observer.New(observerStore, driver, slogLogger)
	httpServer := server.NewHTTPServer(confServer, dcNetLabService, terminalUsecase, observerObserver, history, captureUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, dcNetLabService, logger)
	repoServer := server.NewRepoServer(confServer, packageUsecase, slogLogger)
	metricsStore := data.NewMetricsStore(dataData)
	agent := data.NewMetricsAgent(programAgent)
	collector := metrics.NewCollector(metricsStore, agent, driver, history, slogLogger)
	trafficStore := data.NewTrafficStore(dataData)
	trafficAgent := data.NewTrafficAgent(programAgent)
	trafficCollector := traffic.NewCollector(trafficStore, trafficAgent, driver, trafficUsecase, trafficHistory, slogLogger)
	app := newApp(confServer, logger, httpServer, grpcServer, repoServer, observerObserver, collector, trafficCollector, captureManager)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
