// Agent is the gRPC surface of dcnetlab-agent, the data
// plane daemon running on every machine that hosts lab containers.
// It exposes the runtime driver operations (deploy, exec, faults) the
// controller previously performed through local docker/containerlab
// CLIs, so the controller no longer needs to share a machine with the
// container runtime. The controller is its only client; on a
// single-machine install both talk over localhost.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// runtime_available is true when the containerlab binary and the
	// docker daemon are both usable on this host.
	RuntimeAvailable bool `protobuf:"varint,1,opt,name=runtime_available,json=runtimeAvailable,proto3" json:"runtime_available,omitempty"`
	// detail explains an unavailable runtime (missing binary, daemon
	// down) for the controller's log.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetRuntimeAvailable() bool {
	if x != nil {
		return x.RuntimeAvailable
	}
	return false
}

func (x *PingReply) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// DeployRequest carries a complete generation artifact. key is an
// opaque, path-safe identifier of the generation ("<lab>/<gen>");
// the agent materialises the files under its own data directory at
// that key and runs containerlab there, so repeated calls for the
// same key are idempotent.
type DeployRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// files maps a path relative to the generation directory to its
	// content (topology YAML plus per-node configs).
	Files         map[string][]byte `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DeployRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeployRequest) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

type DeployReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployReply) Reset() {
	*x = DeployReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployReply) ProtoMessage() {}

func (x *DeployReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployReply.ProtoReflect.Descriptor instead.
func (*DeployReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Cmd           []string               `protobuf:"bytes,3,rep,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ExecRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *ExecRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ExecRequest) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type ExecReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// output is the command's combined stdout/stderr, returned also
	// when the command failed (the error arrives as a gRPC status).
	Output        []byte `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecReply) Reset() {
	*x = ExecReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecReply) ProtoMessage() {}

func (x *ExecReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecReply.ProtoReflect.Descriptor instead.
func (*ExecReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExecReply) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type ExecStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start must be set on the first message and only there.
	Start         *ExecRequest `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamRequest) Reset() {
	*x = ExecStreamRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamRequest) ProtoMessage() {}

func (x *ExecStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamRequest.ProtoReflect.Descriptor instead.
func (*ExecStreamRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExecStreamRequest) GetStart() *ExecRequest {
	if x != nil {
		return x.Start
	}
	return nil
}

type ExecStreamReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stdout is one chunk of the command's raw standard output.
	Stdout        []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamReply) Reset() {
	*x = ExecStreamReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamReply) ProtoMessage() {}

func (x *ExecStreamReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamReply.ProtoReflect.Descriptor instead.
func (*ExecStreamReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ExecStreamReply) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type TerminalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start must be set on the first message and only there.
	Start *TerminalStart `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// stdin feeds keystrokes to the shell.
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// resize adjusts the pseudo-terminal window.
	Resize        *TerminalResize `protobuf:"bytes,3,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalRequest) Reset() {
	*x = TerminalRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalRequest) ProtoMessage() {}

func (x *TerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalRequest.ProtoReflect.Descriptor instead.
func (*TerminalRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TerminalRequest) GetStart() *TerminalStart {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TerminalRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *TerminalRequest) GetResize() *TerminalResize {
	if x != nil {
		return x.Resize
	}
	return nil
}

type TerminalStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Cmd           []string               `protobuf:"bytes,3,rep,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalStart) Reset() {
	*x = TerminalStart{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalStart) ProtoMessage() {}

func (x *TerminalStart) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalStart.ProtoReflect.Descriptor instead.
func (*TerminalStart) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TerminalStart) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *TerminalStart) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *TerminalStart) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        []byte                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalReply) Reset() {
	*x = TerminalReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalReply) ProtoMessage() {}

func (x *TerminalReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalReply.ProtoReflect.Descriptor instead.
func (*TerminalReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *TerminalReply) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

type DialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is the "host:port" target on the lab management network;
	// set on the first message and only there.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DialRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DialRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DialReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialReply) Reset() {
	*x = DialReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialReply) ProtoMessage() {}

func (x *DialReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialReply.ProtoReflect.Descriptor instead.
func (*DialReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DialReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodeStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeNames     []string               `protobuf:"bytes,2,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatesRequest) Reset() {
	*x = NodeStatesRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatesRequest) ProtoMessage() {}

func (x *NodeStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatesRequest.ProtoReflect.Descriptor instead.
func (*NodeStatesRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *NodeStatesRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *NodeStatesRequest) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

type NodeStatesReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// states maps node name to its docker container state ("running",
	// "paused", "exited", ... or "missing").
	States        map[string]string `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatesReply) Reset() {
	*x = NodeStatesReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatesReply) ProtoMessage() {}

func (x *NodeStatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatesReply.ProtoReflect.Descriptor instead.
func (*NodeStatesReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *NodeStatesReply) GetStates() map[string]string {
	if x != nil {
		return x.States
	}
	return nil
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *NodeRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *NodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type AddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressReply) Reset() {
	*x = AddressReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressReply) ProtoMessage() {}

func (x *AddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressReply.ProtoReflect.Descriptor instead.
func (*AddressReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type NodeSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeNames     []string               `protobuf:"bytes,2,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSetRequest) Reset() {
	*x = NodeSetRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSetRequest) ProtoMessage() {}

func (x *NodeSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSetRequest.ProtoReflect.Descriptor instead.
func (*NodeSetRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *NodeSetRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *NodeSetRequest) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

type NodeSetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSetReply) Reset() {
	*x = NodeSetReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSetReply) ProtoMessage() {}

func (x *NodeSetReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSetReply.ProtoReflect.Descriptor instead.
func (*NodeSetReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

type EnsureImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureImageRequest) Reset() {
	*x = EnsureImageRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageRequest) ProtoMessage() {}

func (x *EnsureImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageRequest.ProtoReflect.Descriptor instead.
func (*EnsureImageRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *EnsureImageRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type EnsureImageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureImageReply) Reset() {
	*x = EnsureImageReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageReply) ProtoMessage() {}

func (x *EnsureImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageReply.ProtoReflect.Descriptor instead.
func (*EnsureImageReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

type ConnectInternetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectInternetReply) Reset() {
	*x = ConnectInternetReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectInternetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInternetReply) ProtoMessage() {}

func (x *ConnectInternetReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInternetReply.ProtoReflect.Descriptor instead.
func (*ConnectInternetReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

type SetInterfaceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	Up            bool                   `protobuf:"varint,4,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInterfaceStateRequest) Reset() {
	*x = SetInterfaceStateRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInterfaceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceStateRequest) ProtoMessage() {}

func (x *SetInterfaceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceStateRequest.ProtoReflect.Descriptor instead.
func (*SetInterfaceStateRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *SetInterfaceStateRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *SetInterfaceStateRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SetInterfaceStateRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *SetInterfaceStateRequest) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

type SetInterfaceStateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInterfaceStateReply) Reset() {
	*x = SetInterfaceStateReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInterfaceStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceStateReply) ProtoMessage() {}

func (x *SetInterfaceStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceStateReply.ProtoReflect.Descriptor instead.
func (*SetInterfaceStateReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

// Impairment mirrors runtime.Impairment: the netem parameter set of
// one interface. Zero fields are omitted from the qdisc.
type ApplyImpairmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	DelayMs       int32                  `protobuf:"varint,4,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	JitterMs      int32                  `protobuf:"varint,5,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	LossPercent   float64                `protobuf:"fixed64,6,opt,name=loss_percent,json=lossPercent,proto3" json:"loss_percent,omitempty"`
	RateKbit      int32                  `protobuf:"varint,7,opt,name=rate_kbit,json=rateKbit,proto3" json:"rate_kbit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyImpairmentRequest) Reset() {
	*x = ApplyImpairmentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyImpairmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyImpairmentRequest) ProtoMessage() {}

func (x *ApplyImpairmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyImpairmentRequest.ProtoReflect.Descriptor instead.
func (*ApplyImpairmentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ApplyImpairmentRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *ApplyImpairmentRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ApplyImpairmentRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *ApplyImpairmentRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *ApplyImpairmentRequest) GetJitterMs() int32 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *ApplyImpairmentRequest) GetLossPercent() float64 {
	if x != nil {
		return x.LossPercent
	}
	return 0
}

func (x *ApplyImpairmentRequest) GetRateKbit() int32 {
	if x != nil {
		return x.RateKbit
	}
	return 0
}

type ClearImpairmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabName       string                 `protobuf:"bytes,1,opt,name=lab_name,json=labName,proto3" json:"lab_name,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearImpairmentRequest) Reset() {
	*x = ClearImpairmentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearImpairmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearImpairmentRequest) ProtoMessage() {}

func (x *ClearImpairmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearImpairmentRequest.ProtoReflect.Descriptor instead.
func (*ClearImpairmentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *ClearImpairmentRequest) GetLabName() string {
	if x != nil {
		return x.LabName
	}
	return ""
}

func (x *ClearImpairmentRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ClearImpairmentRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type ImpairmentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpairmentReply) Reset() {
	*x = ImpairmentReply{}
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpairmentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpairmentReply) ProtoMessage() {}

func (x *ImpairmentReply) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpairmentReply.ProtoReflect.Descriptor instead.
func (*ImpairmentReply) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\r\n" +
	"\vPingRequest\"P\n" +
	"\tPingReply\x12+\n" +
	"\x11runtime_available\x18\x01 \x01(\bR\x10runtimeAvailable\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x95\x01\n" +
	"\rDeployRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05files\x18\x02 \x03(\v2\".agent.v1.DeployRequest.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\r\n" +
	"\vDeployReply\"W\n" +
	"\vExecRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x10\n" +
	"\x03cmd\x18\x03 \x03(\tR\x03cmd\"#\n" +
	"\tExecReply\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"@\n" +
	"\x11ExecStreamRequest\x12+\n" +
	"\x05start\x18\x01 \x01(\v2\x15.agent.v1.ExecRequestR\x05start\")\n" +
	"\x0fExecStreamReply\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\"\x88\x01\n" +
	"\x0fTerminalRequest\x12-\n" +
	"\x05start\x18\x01 \x01(\v2\x17.agent.v1.TerminalStartR\x05start\x12\x14\n" +
	"\x05stdin\x18\x02 \x01(\fR\x05stdin\x120\n" +
	"\x06resize\x18\x03 \x01(\v2\x18.agent.v1.TerminalResizeR\x06resize\"Y\n" +
	"\rTerminalStart\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x10\n" +
	"\x03cmd\x18\x03 \x03(\tR\x03cmd\"8\n" +
	"\x0eTerminalResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"'\n" +
	"\rTerminalReply\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\fR\x06stdout\";\n" +
	"\vDialRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x1f\n" +
	"\tDialReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"M\n" +
	"\x11NodeStatesRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1d\n" +
	"\n" +
	"node_names\x18\x02 \x03(\tR\tnodeNames\"\x8b\x01\n" +
	"\x0fNodeStatesReply\x12=\n" +
	"\x06states\x18\x01 \x03(\v2%.agent.v1.NodeStatesReply.StatesEntryR\x06states\x1a9\n" +
	"\vStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\vNodeRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"(\n" +
	"\fAddressReply\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"J\n" +
	"\x0eNodeSetRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1d\n" +
	"\n" +
	"node_names\x18\x02 \x03(\tR\tnodeNames\"\x0e\n" +
	"\fNodeSetReply\"*\n" +
	"\x12EnsureImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"\x12\n" +
	"\x10EnsureImageReply\"\x16\n" +
	"\x14ConnectInternetReply\"\x80\x01\n" +
	"\x18SetInterfaceStateRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x0e\n" +
	"\x02up\x18\x04 \x01(\bR\x02up\"\x18\n" +
	"\x16SetInterfaceStateReply\"\xe6\x01\n" +
	"\x16ApplyImpairmentRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x19\n" +
	"\bdelay_ms\x18\x04 \x01(\x05R\adelayMs\x12\x1b\n" +
	"\tjitter_ms\x18\x05 \x01(\x05R\bjitterMs\x12!\n" +
	"\floss_percent\x18\x06 \x01(\x01R\vlossPercent\x12\x1b\n" +
	"\trate_kbit\x18\a \x01(\x05R\brateKbit\"n\n" +
	"\x16ClearImpairmentRequest\x12\x19\n" +
	"\blab_name\x18\x01 \x01(\tR\alabName\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\"\x11\n" +
	"\x0fImpairmentReply2\xf9\b\n" +
	"\x05Agent\x122\n" +
	"\x04Ping\x12\x15.agent.v1.PingRequest\x1a\x13.agent.v1.PingReply\x128\n" +
	"\x06Deploy\x12\x17.agent.v1.DeployRequest\x1a\x15.agent.v1.DeployReply\x129\n" +
	"\aDestroy\x12\x17.agent.v1.DeployRequest\x1a\x15.agent.v1.DeployReply\x122\n" +
	"\x04Exec\x12\x15.agent.v1.ExecRequest\x1a\x13.agent.v1.ExecReply\x12H\n" +
	"\n" +
	"ExecStream\x12\x1b.agent.v1.ExecStreamRequest\x1a\x19.agent.v1.ExecStreamReply(\x010\x01\x12B\n" +
	"\bTerminal\x12\x19.agent.v1.TerminalRequest\x1a\x17.agent.v1.TerminalReply(\x010\x01\x126\n" +
	"\x04Dial\x12\x15.agent.v1.DialRequest\x1a\x13.agent.v1.DialReply(\x010\x01\x12D\n" +
	"\n" +
	"NodeStates\x12\x1b.agent.v1.NodeStatesRequest\x1a\x19.agent.v1.NodeStatesReply\x12<\n" +
	"\vNodeAddress\x12\x15.agent.v1.NodeRequest\x1a\x16.agent.v1.AddressReply\x12<\n" +
	"\vNodeGateway\x12\x15.agent.v1.NodeRequest\x1a\x16.agent.v1.AddressReply\x12>\n" +
	"\n" +
	"StartNodes\x12\x18.agent.v1.NodeSetRequest\x1a\x16.agent.v1.NodeSetReply\x12=\n" +
	"\tStopNodes\x12\x18.agent.v1.NodeSetRequest\x1a\x16.agent.v1.NodeSetReply\x12G\n" +
	"\vEnsureImage\x12\x1c.agent.v1.EnsureImageRequest\x1a\x1a.agent.v1.EnsureImageReply\x12H\n" +
	"\x0fConnectInternet\x12\x15.agent.v1.NodeRequest\x1a\x1e.agent.v1.ConnectInternetReply\x12Y\n" +
	"\x11SetInterfaceState\x12\".agent.v1.SetInterfaceStateRequest\x1a .agent.v1.SetInterfaceStateReply\x12N\n" +
	"\x0fApplyImpairment\x12 .agent.v1.ApplyImpairmentRequest\x1a\x19.agent.v1.ImpairmentReply\x12N\n" +
	"\x0fClearImpairment\x12 .agent.v1.ClearImpairmentRequest\x1a\x19.agent.v1.ImpairmentReplyB-Z+github.com/ifantsai/dcnetlab/pb/agent/v1;v1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_agent_v1_agent_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: agent.v1.PingRequest
	(*PingReply)(nil),                // 1: agent.v1.PingReply
	(*DeployRequest)(nil),            // 2: agent.v1.DeployRequest
	(*DeployReply)(nil),              // 3: agent.v1.DeployReply
	(*ExecRequest)(nil),              // 4: agent.v1.ExecRequest
	(*ExecReply)(nil),                // 5: agent.v1.ExecReply
	(*ExecStreamRequest)(nil),        // 6: agent.v1.ExecStreamRequest
	(*ExecStreamReply)(nil),          // 7: agent.v1.ExecStreamReply
	(*TerminalRequest)(nil),          // 8: agent.v1.TerminalRequest
	(*TerminalStart)(nil),            // 9: agent.v1.TerminalStart
	(*TerminalResize)(nil),           // 10: agent.v1.TerminalResize
	(*TerminalReply)(nil),            // 11: agent.v1.TerminalReply
	(*DialRequest)(nil),              // 12: agent.v1.DialRequest
	(*DialReply)(nil),                // 13: agent.v1.DialReply
	(*NodeStatesRequest)(nil),        // 14: agent.v1.NodeStatesRequest
	(*NodeStatesReply)(nil),          // 15: agent.v1.NodeStatesReply
	(*NodeRequest)(nil),              // 16: agent.v1.NodeRequest
	(*AddressReply)(nil),             // 17: agent.v1.AddressReply
	(*NodeSetRequest)(nil),           // 18: agent.v1.NodeSetRequest
	(*NodeSetReply)(nil),             // 19: agent.v1.NodeSetReply
	(*EnsureImageRequest)(nil),       // 20: agent.v1.EnsureImageRequest
	(*EnsureImageReply)(nil),         // 21: agent.v1.EnsureImageReply
	(*ConnectInternetReply)(nil),     // 22: agent.v1.ConnectInternetReply
	(*SetInterfaceStateRequest)(nil), // 23: agent.v1.SetInterfaceStateRequest
	(*SetInterfaceStateReply)(nil),   // 24: agent.v1.SetInterfaceStateReply
	(*ApplyImpairmentRequest)(nil),   // 25: agent.v1.ApplyImpairmentRequest
	(*ClearImpairmentRequest)(nil),   // 26: agent.v1.ClearImpairmentRequest
	(*ImpairmentReply)(nil),          // 27: agent.v1.ImpairmentReply
	nil,                              // 28: agent.v1.DeployRequest.FilesEntry
	nil,                              // 29: agent.v1.NodeStatesReply.StatesEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	28, // 0: agent.v1.DeployRequest.files:type_name -> agent.v1.DeployRequest.FilesEntry
	4,  // 1: agent.v1.ExecStreamRequest.start:type_name -> agent.v1.ExecRequest
	9,  // 2: agent.v1.TerminalRequest.start:type_name -> agent.v1.TerminalStart
	10, // 3: agent.v1.TerminalRequest.resize:type_name -> agent.v1.TerminalResize
	29, // 4: agent.v1.NodeStatesReply.states:type_name -> agent.v1.NodeStatesReply.StatesEntry
	0,  // 5: agent.v1.Agent.Ping:input_type -> agent.v1.PingRequest
	2,  // 6: agent.v1.Agent.Deploy:input_type -> agent.v1.DeployRequest
	2,  // 7: agent.v1.Agent.Destroy:input_type -> agent.v1.DeployRequest
	4,  // 8: agent.v1.Agent.Exec:input_type -> agent.v1.ExecRequest
	6,  // 9: agent.v1.Agent.ExecStream:input_type -> agent.v1.ExecStreamRequest
	8,  // 10: agent.v1.Agent.Terminal:input_type -> agent.v1.TerminalRequest
	12, // 11: agent.v1.Agent.Dial:input_type -> agent.v1.DialRequest
	14, // 12: agent.v1.Agent.NodeStates:input_type -> agent.v1.NodeStatesRequest
	16, // 13: agent.v1.Agent.NodeAddress:input_type -> agent.v1.NodeRequest
	16, // 14: agent.v1.Agent.NodeGateway:input_type -> agent.v1.NodeRequest
	18, // 15: agent.v1.Agent.StartNodes:input_type -> agent.v1.NodeSetRequest
	18, // 16: agent.v1.Agent.StopNodes:input_type -> agent.v1.NodeSetRequest
	20, // 17: agent.v1.Agent.EnsureImage:input_type -> agent.v1.EnsureImageRequest
	16, // 18: agent.v1.Agent.ConnectInternet:input_type -> agent.v1.NodeRequest
	23, // 19: agent.v1.Agent.SetInterfaceState:input_type -> agent.v1.SetInterfaceStateRequest
	25, // 20: agent.v1.Agent.ApplyImpairment:input_type -> agent.v1.ApplyImpairmentRequest
	26, // 21: agent.v1.Agent.ClearImpairment:input_type -> agent.v1.ClearImpairmentRequest
	1,  // 22: agent.v1.Agent.Ping:output_type -> agent.v1.PingReply
	3,  // 23: agent.v1.Agent.Deploy:output_type -> agent.v1.DeployReply
	3,  // 24: agent.v1.Agent.Destroy:output_type -> agent.v1.DeployReply
	5,  // 25: agent.v1.Agent.Exec:output_type -> agent.v1.ExecReply
	7,  // 26: agent.v1.Agent.ExecStream:output_type -> agent.v1.ExecStreamReply
	11, // 27: agent.v1.Agent.Terminal:output_type -> agent.v1.TerminalReply
	13, // 28: agent.v1.Agent.Dial:output_type -> agent.v1.DialReply
	15, // 29: agent.v1.Agent.NodeStates:output_type -> agent.v1.NodeStatesReply
	17, // 30: agent.v1.Agent.NodeAddress:output_type -> agent.v1.AddressReply
	17, // 31: agent.v1.Agent.NodeGateway:output_type -> agent.v1.AddressReply
	19, // 32: agent.v1.Agent.StartNodes:output_type -> agent.v1.NodeSetReply
	19, // 33: agent.v1.Agent.StopNodes:output_type -> agent.v1.NodeSetReply
	21, // 34: agent.v1.Agent.EnsureImage:output_type -> agent.v1.EnsureImageReply
	22, // 35: agent.v1.Agent.ConnectInternet:output_type -> agent.v1.ConnectInternetReply
	24, // 36: agent.v1.Agent.SetInterfaceState:output_type -> agent.v1.SetInterfaceStateReply
	27, // 37: agent.v1.Agent.ApplyImpairment:output_type -> agent.v1.ImpairmentReply
	27, // 38: agent.v1.Agent.ClearImpairment:output_type -> agent.v1.ImpairmentReply
	22, // [22:39] is the sub-list for method output_type
	5,  // [5:22] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
