// Agent is the gRPC surface of dcnetlab-agent, the data
// plane daemon running on every machine that hosts lab containers.
// It exposes the runtime driver operations (deploy, exec, faults) the
// controller previously performed through local docker/containerlab
// CLIs, so the controller no longer needs to share a machine with the
// container runtime. The controller is its only client; on a
// single-machine install both talk over localhost.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: agent/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Ping_FullMethodName              = "/agent.v1.Agent/Ping"
	Agent_Deploy_FullMethodName            = "/agent.v1.Agent/Deploy"
	Agent_Destroy_FullMethodName           = "/agent.v1.Agent/Destroy"
	Agent_Exec_FullMethodName              = "/agent.v1.Agent/Exec"
	Agent_ExecStream_FullMethodName        = "/agent.v1.Agent/ExecStream"
	Agent_Terminal_FullMethodName          = "/agent.v1.Agent/Terminal"
	Agent_Dial_FullMethodName              = "/agent.v1.Agent/Dial"
	Agent_NodeStates_FullMethodName        = "/agent.v1.Agent/NodeStates"
	Agent_NodeAddress_FullMethodName       = "/agent.v1.Agent/NodeAddress"
	Agent_NodeGateway_FullMethodName       = "/agent.v1.Agent/NodeGateway"
	Agent_StartNodes_FullMethodName        = "/agent.v1.Agent/StartNodes"
	Agent_StopNodes_FullMethodName         = "/agent.v1.Agent/StopNodes"
	Agent_EnsureImage_FullMethodName       = "/agent.v1.Agent/EnsureImage"
	Agent_ConnectInternet_FullMethodName   = "/agent.v1.Agent/ConnectInternet"
	Agent_SetInterfaceState_FullMethodName = "/agent.v1.Agent/SetInterfaceState"
	Agent_ApplyImpairment_FullMethodName   = "/agent.v1.Agent/ApplyImpairment"
	Agent_ClearImpairment_FullMethodName   = "/agent.v1.Agent/ClearImpairment"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// Ping reports the agent is reachable and whether the containerlab
	// runtime behind it is usable; the controller calls it at startup
	// to decide between the agent and noop drivers.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// Deploy materialises the artifact files under the agent's data
	// directory and runs `containerlab deploy` on them.
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	// Destroy materialises the artifact files (the agent may have been
	// reinstalled since the deploy) and runs `containerlab destroy`.
	Destroy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	// Exec runs one command inside a lab container and returns its
	// combined output.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecReply, error)
	// ExecStream runs a long-lived non-interactive command inside a lab
	// container. The client sends Start first; the server streams raw
	// stdout chunks. Closing the client side closes the command's
	// stdin — the in-container tool's stop signal — after which the
	// server reaps the process and ends the stream.
	ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamReply], error)
	// Terminal attaches an interactive shell inside a lab container
	// under a pseudo-terminal. The client sends Start first, then
	// stdin bytes and resize events; the server streams terminal
	// output.
	Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalRequest, TerminalReply], error)
	// Dial proxies one TCP connection into the lab management network
	// (e.g. to a node-agent's gRPC port). The client sends Start with
	// the target address, then payload bytes; the server relays bytes
	// both ways until either side closes.
	Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialRequest, DialReply], error)
	// NodeStates reports the live container state of each named node.
	NodeStates(ctx context.Context, in *NodeStatesRequest, opts ...grpc.CallOption) (*NodeStatesReply, error)
	// NodeAddress returns a node's management-network IP.
	NodeAddress(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressReply, error)
	// NodeGateway returns the host-side gateway IP of a node's
	// management network.
	NodeGateway(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressReply, error)
	// StartNodes resumes previously stopped (frozen) nodes.
	StartNodes(ctx context.Context, in *NodeSetRequest, opts ...grpc.CallOption) (*NodeSetReply, error)
	// StopNodes freezes the named nodes in place (docker pause).
	StopNodes(ctx context.Context, in *NodeSetRequest, opts ...grpc.CallOption) (*NodeSetReply, error)
	// EnsureImage verifies a container image is available on the host.
	EnsureImage(ctx context.Context, in *EnsureImageRequest, opts ...grpc.CallOption) (*EnsureImageReply, error)
	// ConnectInternet attaches a node to the shared WAN network and
	// routes its non-fabric traffic to the real internet.
	ConnectInternet(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*ConnectInternetReply, error)
	// SetInterfaceState brings a node's interface administratively up
	// or down.
	SetInterfaceState(ctx context.Context, in *SetInterfaceStateRequest, opts ...grpc.CallOption) (*SetInterfaceStateReply, error)
	// ApplyImpairment shapes egress traffic on a node's interface with
	// a netem qdisc.
	ApplyImpairment(ctx context.Context, in *ApplyImpairmentRequest, opts ...grpc.CallOption) (*ImpairmentReply, error)
	// ClearImpairment removes a previously applied netem qdisc; a no-op
	// if none is present.
	ClearImpairment(ctx context.Context, in *ClearImpairmentRequest, opts ...grpc.CallOption) (*ImpairmentReply, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, Agent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployReply)
	err := c.cc.Invoke(ctx, Agent_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Destroy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployReply)
	err := c.cc.Invoke(ctx, Agent_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecReply)
	err := c.cc.Invoke(ctx, Agent_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ExecStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], Agent_ExecStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecStreamRequest, ExecStreamReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ExecStreamClient = grpc.BidiStreamingClient[ExecStreamRequest, ExecStreamReply]

func (c *agentClient) Terminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalRequest, TerminalReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], Agent_Terminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalRequest, TerminalReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_TerminalClient = grpc.BidiStreamingClient[TerminalRequest, TerminalReply]

func (c *agentClient) Dial(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DialRequest, DialReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[2], Agent_Dial_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DialRequest, DialReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_DialClient = grpc.BidiStreamingClient[DialRequest, DialReply]

func (c *agentClient) NodeStates(ctx context.Context, in *NodeStatesRequest, opts ...grpc.CallOption) (*NodeStatesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatesReply)
	err := c.cc.Invoke(ctx, Agent_NodeStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) NodeAddress(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressReply)
	err := c.cc.Invoke(ctx, Agent_NodeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) NodeGateway(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*AddressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressReply)
	err := c.cc.Invoke(ctx, Agent_NodeGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StartNodes(ctx context.Context, in *NodeSetRequest, opts ...grpc.CallOption) (*NodeSetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSetReply)
	err := c.cc.Invoke(ctx, Agent_StartNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopNodes(ctx context.Context, in *NodeSetRequest, opts ...grpc.CallOption) (*NodeSetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSetReply)
	err := c.cc.Invoke(ctx, Agent_StopNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) EnsureImage(ctx context.Context, in *EnsureImageRequest, opts ...grpc.CallOption) (*EnsureImageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureImageReply)
	err := c.cc.Invoke(ctx, Agent_EnsureImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ConnectInternet(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*ConnectInternetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectInternetReply)
	err := c.cc.Invoke(ctx, Agent_ConnectInternet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SetInterfaceState(ctx context.Context, in *SetInterfaceStateRequest, opts ...grpc.CallOption) (*SetInterfaceStateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInterfaceStateReply)
	err := c.cc.Invoke(ctx, Agent_SetInterfaceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ApplyImpairment(ctx context.Context, in *ApplyImpairmentRequest, opts ...grpc.CallOption) (*ImpairmentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpairmentReply)
	err := c.cc.Invoke(ctx, Agent_ApplyImpairment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ClearImpairment(ctx context.Context, in *ClearImpairmentRequest, opts ...grpc.CallOption) (*ImpairmentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImpairmentReply)
	err := c.cc.Invoke(ctx, Agent_ClearImpairment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
type AgentServer interface {
	// Ping reports the agent is reachable and whether the containerlab
	// runtime behind it is usable; the controller calls it at startup
	// to decide between the agent and noop drivers.
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// Deploy materialises the artifact files under the agent's data
	// directory and runs `containerlab deploy` on them.
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	// Destroy materialises the artifact files (the agent may have been
	// reinstalled since the deploy) and runs `containerlab destroy`.
	Destroy(context.Context, *DeployRequest) (*DeployReply, error)
	// Exec runs one command inside a lab container and returns its
	// combined output.
	Exec(context.Context, *ExecRequest) (*ExecReply, error)
	// ExecStream runs a long-lived non-interactive command inside a lab
	// container. The client sends Start first; the server streams raw
	// stdout chunks. Closing the client side closes the command's
	// stdin — the in-container tool's stop signal — after which the
	// server reaps the process and ends the stream.
	ExecStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamReply]) error
	// Terminal attaches an interactive shell inside a lab container
	// under a pseudo-terminal. The client sends Start first, then
	// stdin bytes and resize events; the server streams terminal
	// output.
	Terminal(grpc.BidiStreamingServer[TerminalRequest, TerminalReply]) error
	// Dial proxies one TCP connection into the lab management network
	// (e.g. to a node-agent's gRPC port). The client sends Start with
	// the target address, then payload bytes; the server relays bytes
	// both ways until either side closes.
	Dial(grpc.BidiStreamingServer[DialRequest, DialReply]) error
	// NodeStates reports the live container state of each named node.
	NodeStates(context.Context, *NodeStatesRequest) (*NodeStatesReply, error)
	// NodeAddress returns a node's management-network IP.
	NodeAddress(context.Context, *NodeRequest) (*AddressReply, error)
	// NodeGateway returns the host-side gateway IP of a node's
	// management network.
	NodeGateway(context.Context, *NodeRequest) (*AddressReply, error)
	// StartNodes resumes previously stopped (frozen) nodes.
	StartNodes(context.Context, *NodeSetRequest) (*NodeSetReply, error)
	// StopNodes freezes the named nodes in place (docker pause).
	StopNodes(context.Context, *NodeSetRequest) (*NodeSetReply, error)
	// EnsureImage verifies a container image is available on the host.
	EnsureImage(context.Context, *EnsureImageRequest) (*EnsureImageReply, error)
	// ConnectInternet attaches a node to the shared WAN network and
	// routes its non-fabric traffic to the real internet.
	ConnectInternet(context.Context, *NodeRequest) (*ConnectInternetReply, error)
	// SetInterfaceState brings a node's interface administratively up
	// or down.
	SetInterfaceState(context.Context, *SetInterfaceStateRequest) (*SetInterfaceStateReply, error)
	// ApplyImpairment shapes egress traffic on a node's interface with
	// a netem qdisc.
	ApplyImpairment(context.Context, *ApplyImpairmentRequest) (*ImpairmentReply, error)
	// ClearImpairment removes a previously applied netem qdisc; a no-op
	// if none is present.
	ClearImpairment(context.Context, *ClearImpairmentRequest) (*ImpairmentReply, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServer) Deploy(context.Context, *DeployRequest) (*DeployReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedAgentServer) Destroy(context.Context, *DeployRequest) (*DeployReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedAgentServer) Exec(context.Context, *ExecRequest) (*ExecReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedAgentServer) ExecStream(grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamReply]) error {
	return status.Errorf(codes.Unimplemented, "method ExecStream not implemented")
}
func (UnimplementedAgentServer) Terminal(grpc.BidiStreamingServer[TerminalRequest, TerminalReply]) error {
	return status.Errorf(codes.Unimplemented, "method Terminal not implemented")
}
func (UnimplementedAgentServer) Dial(grpc.BidiStreamingServer[DialRequest, DialReply]) error {
	return status.Errorf(codes.Unimplemented, "method Dial not implemented")
}
func (UnimplementedAgentServer) NodeStates(context.Context, *NodeStatesRequest) (*NodeStatesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeStates not implemented")
}
func (UnimplementedAgentServer) NodeAddress(context.Context, *NodeRequest) (*AddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAddress not implemented")
}
func (UnimplementedAgentServer) NodeGateway(context.Context, *NodeRequest) (*AddressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeGateway not implemented")
}
func (UnimplementedAgentServer) StartNodes(context.Context, *NodeSetRequest) (*NodeSetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartNodes not implemented")
}
func (UnimplementedAgentServer) StopNodes(context.Context, *NodeSetRequest) (*NodeSetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopNodes not implemented")
}
func (UnimplementedAgentServer) EnsureImage(context.Context, *EnsureImageRequest) (*EnsureImageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureImage not implemented")
}
func (UnimplementedAgentServer) ConnectInternet(context.Context, *NodeRequest) (*ConnectInternetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectInternet not implemented")
}
func (UnimplementedAgentServer) SetInterfaceState(context.Context, *SetInterfaceStateRequest) (*SetInterfaceStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInterfaceState not implemented")
}
func (UnimplementedAgentServer) ApplyImpairment(context.Context, *ApplyImpairmentRequest) (*ImpairmentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyImpairment not implemented")
}
func (UnimplementedAgentServer) ClearImpairment(context.Context, *ClearImpairmentRequest) (*ImpairmentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearImpairment not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call pancis, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Destroy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ExecStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).ExecStream(&grpc.GenericServerStream[ExecStreamRequest, ExecStreamReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_ExecStreamServer = grpc.BidiStreamingServer[ExecStreamRequest, ExecStreamReply]

func _Agent_Terminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Terminal(&grpc.GenericServerStream[TerminalRequest, TerminalReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_TerminalServer = grpc.BidiStreamingServer[TerminalRequest, TerminalReply]

func _Agent_Dial_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Dial(&grpc.GenericServerStream[DialRequest, DialReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Agent_DialServer = grpc.BidiStreamingServer[DialRequest, DialReply]

func _Agent_NodeStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).NodeStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_NodeStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).NodeStates(ctx, req.(*NodeStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_NodeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).NodeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_NodeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).NodeAddress(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_NodeGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).NodeGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_NodeGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).NodeGateway(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StartNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StartNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StartNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StartNodes(ctx, req.(*NodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StopNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopNodes(ctx, req.(*NodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_EnsureImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).EnsureImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_EnsureImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).EnsureImage(ctx, req.(*EnsureImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ConnectInternet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ConnectInternet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ConnectInternet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ConnectInternet(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SetInterfaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInterfaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SetInterfaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_SetInterfaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SetInterfaceState(ctx, req.(*SetInterfaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ApplyImpairment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyImpairmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ApplyImpairment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ApplyImpairment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ApplyImpairment(ctx, req.(*ApplyImpairmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ClearImpairment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearImpairmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ClearImpairment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ClearImpairment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ClearImpairment(ctx, req.(*ClearImpairmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Agent_Ping_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _Agent_Deploy_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Agent_Destroy_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _Agent_Exec_Handler,
		},
		{
			MethodName: "NodeStates",
			Handler:    _Agent_NodeStates_Handler,
		},
		{
			MethodName: "NodeAddress",
			Handler:    _Agent_NodeAddress_Handler,
		},
		{
			MethodName: "NodeGateway",
			Handler:    _Agent_NodeGateway_Handler,
		},
		{
			MethodName: "StartNodes",
			Handler:    _Agent_StartNodes_Handler,
		},
		{
			MethodName: "StopNodes",
			Handler:    _Agent_StopNodes_Handler,
		},
		{
			MethodName: "EnsureImage",
			Handler:    _Agent_EnsureImage_Handler,
		},
		{
			MethodName: "ConnectInternet",
			Handler:    _Agent_ConnectInternet_Handler,
		},
		{
			MethodName: "SetInterfaceState",
			Handler:    _Agent_SetInterfaceState_Handler,
		},
		{
			MethodName: "ApplyImpairment",
			Handler:    _Agent_ApplyImpairment_Handler,
		},
		{
			MethodName: "ClearImpairment",
			Handler:    _Agent_ClearImpairment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecStream",
			Handler:       _Agent_ExecStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Terminal",
			Handler:       _Agent_Terminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Dial",
			Handler:       _Agent_Dial_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
